### ISSUE TITLE
Test on Windows 7

### ISSUE THREAD

**Issue by bryanhelmig** [zapier/zapier-platform-cli#1]
We need to make sure the "tutorial" section works fine on Windows 7 as a part of QA'ing releases.

**Comment by bryanhelmig** [comment]
![fail-copy](https://cloud.githubusercontent.com/assets/534177/19875062/0a06af0e-9f87-11e6-9069-d307cdac9b70.png)

**Comment by bryanhelmig** [comment]
Just tested on a Windows 7 VM (SP1) and got a build to work fine.

The fetch() -> buffer() -> saving zip is producing corrupted stuff.

**Comment by carlospaiva** [comment]
The solution can be found here: [http://stackoverflow.com/questions/41944196/zapier-platform-cli-init-error-enoent-no-such-file-or-directory/41945578#41945578](url)

**Comment by bryanhelmig** [comment]
Thank you for the report @carlospaiva - sounds like that is a Powershell specific TMP/TEMP dir variable?

**Comment by carlospaiva** [comment]
It is an environment variable common to all shells.

**Comment by bcooksey** [comment]
Ran through `login`, `register`, `init`, `test`, `validate`, and `push` in Powershell on Windows 10 and all those look good now!
