### ISSUE TITLE
Cannot see my app in dashboard after zapier push

### ISSUE THREAD

**Issue by sungwoncho** [zapier/zapier-platform-cli#10]
node version: 4.3.2
cli version: 0.9.9
os: OSX El Capitan 10.11.12

--

I cannot see my app on https://testing.zapier.com/app/editor after a successful `zapier push`.

Reproduction:
1. Follow the tutorial and run `zapier push` as instructed [here](https://github.com/zapier/zapier-platform-cli#deploying-an-app).

2. Go to https://testing.zapier.com/app/editor as instructed in the success message.

3. The page redirects to 'Edit Step' page (https://testing.zapier.com/app/editor/13728700/nodes/13728700/app).

**Comment by bryanhelmig** [comment]
Don't use testing.zapier.com - use zapier.com - we'll update the instructions.

Also, try shift-clicking refresh to clear your browser cache!

**Comment by sungwoncho** [comment]
@bryanhelmig I have gone through step 1~3 and went to https://zapier.com/app/editor as per instruction. However I am still redirected to https://zapier.com/app/editor/13753968?is_new=true and then https://zapier.com/app/editor/13753968/nodes/13753968/app (shown in the picture).

![edit_step_-_zapier_and_1__mikecho_mikes-macbook-air____dev_tmp_what__zsh_](https://cloud.githubusercontent.com/assets/8265228/20368039/5ef3b5b2-aca6-11e6-96d7-a18950dcae0e.png)


What might be the problem? Happy to make a PR.

**Comment by bryanhelmig** [comment]
Try searching for your app @sungwoncho - you should see:

![](https://zapier.cachefly.net/storage/photos/db1b3714984e9c6b834781cfe939bd8e.png)

I'm closing this issue. Come visit us https://zapier-platform-slack.herokuapp.com/. This tracker is probably not appropriate for such generalized debugging.

**Comment by sungwoncho** [comment]
Thanks @bryanhelmig

As a user, I expected to see a dashboard where I can edit my apps. That's where the confusion arose.
