### ISSUE TITLE
`zapier build` doesn't directly call `zapier validate`

### ISSUE THREAD

**Issue by xavdid** [zapier/zapier-platform-cli#103]
I noticed this when making a validation-related fix. `zapier build` says it validates your project. It uses `_appCommandZapierWrapper`, which in turn wraps core's `schemaTools.validateApp`([source](https://github.com/zapier/zapier-platform-core/blob/master/src/tools/schema.js#L121-L125)). 

This is mostly fine, but that means any extra validation that happens as part of the `validate` command (in this case, running style checks), only happens when `validate` is called directly, but not during `build`. 

Resolution would be to wrap the `validate` command in `cli` rather than going straight to `core`.

**Comment by BrunoBernardino** [comment]
Tracking in PR.
