### ISSUE TITLE
Upgrade supported node versions?

### ISSUE THREAD

**Issue by bcooksey** [zapier/zapier-platform-cli#108]
Node.js had a [severe vulnerability](https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/) patched recently. It involves bumping versions on v4 and v6. We have code that explicitly checks the versions of node used. Wondering if we should update those checks to the new versions.

Bit tricky, as it would be good for us to patch the CLI tool to support the updated versions. However, we've pegged cli and core to the node versions that AWS Lambda supports. At this point, our options are:

 * Bump CLI tool now, leave core lib until Lambda supports update
 * Wait on both until Lambda updates
 * Maybe lambda never updates, so we don't care?

**Comment by BrunoBernardino** [comment]
I'd say this makes sense when lambda updates, otherwise it'll be much harder to maintain.

I think it's safe to close this due to its age.
