### ISSUE TITLE
`zapier init . --template=files` resulting in error

### ISSUE THREAD

**Issue by reganstarr** [zapier/zapier-platform-cli#110]
When I run `zapier init . --template=files` I get

```
Errors running command zapier init . --template=files:

!!!   Unexpected keyword argument --template=files, must be one of {minimal,resource,trigger,create,search,middleware,basic-auth,custom-auth,oauth2,session-auth,babel}
```

According to our [docs](https://github.com/zapier/zapier-platform-cli/wiki/Example-Apps#files-example-app), `--template=files` should be an acceptable argument.

**Comment by BrunoBernardino** [comment]
This has been fixed (confirmed now in 4.0.0).
