### ISSUE TITLE
Using list: true and dict: true together in inputFields doesn't show in bundle.inputData

### ISSUE THREAD

**Issue by BrunoBernardino** [zapier/zapier-platform-cli#114]
Reported at https://zapier-platform.slack.com/archives/C2S5DGF6G/p1501105997537626.

Basically, if `inputFields` has a field like `{ key: "phones", label: "Phones (label | phone number)", list: true, dict: true, default: "defaut" },`, the data shows in `bundle.inputDataRaw` but not `bundle.inputData`. Maybe it's somewhat related to https://github.com/zapier/zapier-platform-core/issues/40 but I'm not entirely sure (this field doesn't need to be custom).

**Comment by BrunoBernardino** [comment]
Note this _might_ be a UI limitation (do we show dicts and lists for any other app? It's usually one or the other), but if it is, we should prevent this combination by schema validation.

**Comment by ZenCocoon** [comment]
UI wise it looks great right now

![http://share.bookingsync.com/1L1i1Z0k1P1V/Image%202017-07-27%20at%202.54.23%20PM.png](http://share.bookingsync.com/1L1i1Z0k1P1V/Image%202017-07-27%20at%202.54.23%20PM.png)

**Comment by BrunoBernardino** [comment]
@ZenCocoon that's the UI for a `dict` (you're adding properties), which I'm guessing is superseding the `list` one.

**Comment by ZenCocoon** [comment]
@BrunoBernardino hoo ok. Wel,l that's what I aimed for actually here. I fixed my personal needs right now using only `dict`.

My ideal way would be to support for `list` + `children` however, this would be the best. :)
Thanks a lot for this amazing software and support.

**Comment by BrunoBernardino** [comment]
Alright! I'll close this and I've opened a different issue for that, where I need some input: https://github.com/zapier/zapier-platform-cli/issues/115
