### ISSUE TITLE
Zapier Java integration

### ISSUE THREAD

**Issue by Lechucico** [zapier/zapier-platform-cli#120]
I'm currently developing a java REST service. I need to know how I can create ZAPS from that java REST.

The flow would be the following:

1. A new user wants to add the gmail integration.
2. I make an ¿API REQUEST? to zapier to ask a new ZAP.
3. Zapier makes the process and get access to the new service.
4. Now that is created, i will receive the notifications once that zap is triggered.

Below is an image of that flow:
![imagen](https://user-images.githubusercontent.com/22009615/29023276-4c9612b6-7b6d-11e7-8d8d-605b011afcb9.png)

I've only seen the javascript CLI. There is any other way of doing this trought java? In case it is not possible, how I can integrate that CLI on my java REST service?

**Comment by bryanhelmig** [comment]
@Lechucico you cannot "create Zaps" via any language (we do not support it) -- only users can create Zaps via the web interface.

You can write a CLI integration to an existing public REST API -- no matter what it is written in. I hope that clarifies this!
