### ISSUE TITLE
process.env.VAR isn't being set for help text

### ISSUE THREAD

**Issue by BrunoBernardino** [zapier/zapier-platform-cli#123]
### Actual Behavior

A developer is getting an error if they use a `process.env.VAR` for a auth field help text (saying we require a URL — which we should probably reconsider tweaking), and if they change it to a function, `process.env.VAR` is undefined.

### Expected Behavior

The developer should be able to use `process.env.VAR` without an error or problem.

### Resources

- Slack conversation with more details: https://zapier-platform.slack.com/archives/C2S5DGF6G/p1503344688000411
- Internal issue with "permanent" pastebin: https://github.com/zapier/zapier/issues/12997

**Comment by pidov** [comment]
+1. 

I'm trying to add a link to register page in the helpText for username. I want to have the URL defined as environment variable. Currently it says that the var is undefined.

**Comment by timsim00** [comment]
+1

Using helpText to include a link to get the API key.  Need the link to be influenced by environment var.

**Comment by BrunoBernardino** [comment]
@pidov / @timsim00 if you make the fields dynamically generated (i.e. returned by a function), it should work for you. Can you please confirm that?

**Comment by pidov** [comment]
@BrunoBernardino I depend on this variable (currently not because I hardcoded the value in my code) not only in fields array, thus I don't think the proposed solution will work for my usecase.

I'm trying to use this as a switch between dev and prod environment and am using different urls based on the value of the env variable. 

I have constants file that looks similar this:
constants.js
```js
const config = getConfig(process.env.ENVIRONMENT) // Currenlty getConfig('development') and manually switching the string in the code.
const { baseUrl } = config

exports.example {
  authorize: `${baseUrl}/authorize'
}
```

I'm then trying to use it in authentication.js like this:

```js
const { example } = require('./constants')
const { authorize } = example

const getToken = (z, bundle) => {
  return z.request({
    method: 'POST',
    url: authorize,
    ...
  })
}
```

Do you have any suggestions for this use case?

**Comment by BrunoBernardino** [comment]
It should be working in that scenario, because any invokation of a method should populate `process.env.VAR` (the problem with non-dynamic help texts is we get the strings without any invoke of any method as it's in the json definition as a string).

If that isn't working for you, would you mind writing into partners@zapier.com with your app id and a Zap id you've tested with so we can take a closer look?

**Comment by BrunoBernardino** [comment]
I'm closing this as the suggestion I provided works in production, and we'd prefer that over always evaluating fields. If you still have issues please reopen this issue with more info and we can figure out the specificity of them.

Thank you so much for your patience!

**Comment by rishikapadia1** [comment]
@BrunoBernardino 
I tried accordingly you suggested but it looks not working.
const getFields = (z, bundle) => {
  return [
    {
      key: 'address',
      label: 'Address',
      helpText: `This will render variables like ${process.env.VAR}.`
    }
  ];
};
Code:
![image](https://user-images.githubusercontent.com/4904333/35454025-55c5996c-02f2-11e8-853b-d2f9533c88ee.png)
ENV updates:
![image](https://user-images.githubusercontent.com/4904333/35454056-7d96e9e6-02f2-11e8-891d-8123a025ebd8.png)
Web UI:
![image](https://user-images.githubusercontent.com/4904333/35454038-6a65cd2e-02f2-11e8-8052-321912d53c3c.png)

**Comment by BrunoBernardino** [comment]
@rishikapadia1 that doesn't look like it's being called by a method. Please try:

```js
const getFields = (z, bundle) => {
  return [
    {
      key: 'address',
      label: 'Address',
      helpText: () => `This will render variables like ${process.env.VAR}.`
    }
  ];
};
```

**Comment by rishikapadia1** [comment]
@BrunoBernardino I just tried but I am seeing this.
UI:
![image](https://user-images.githubusercontent.com/4904333/35648924-59a9d138-06fd-11e8-8ac8-04e9dbdd27e6.png)
Code:
![image](https://user-images.githubusercontent.com/4904333/35648911-4c65cea0-06fd-11e8-9dec-a51f09fa765e.png)
I also tried this.
![image](https://user-images.githubusercontent.com/4904333/35648953-79bbc09e-06fd-11e8-8f14-c53af430aa0d.png)

**Comment by pidov** [comment]
Looks like the parser doesn't execute the function, but serializes the value of ```helptext``` instead.

**Comment by BrunoBernardino** [comment]
I might be missing something here, or something changed.

I guess this needs to be looked into by someone available (I'm on parental leave right now). Please bring it up to partners@zapier.com.

**Comment by rishikapadia1** [comment]
@BrunoBernardino  Thanks for quick response, I sent a mail to partners@zapier.com.

**Comment by eliangcs** [comment]
Looks like we need to reopen this issue as we don't really allow dynamic fields to be used in authentication fields. Unlike`inputFields` and `outputFields` in a create/trigger/search, `fields` in [`AuthenticationSchema`](https://zapier.github.io/zapier-platform-schema/build/schema.html#authenticationschema) is a `FieldsSchema` instead of a `DynamicFieldsSchema`.

**Comment by BradStell** [comment]
Any news on this guys? @BrunoBernardino @eliangcs ? I am also currently trying to have my help text link to an URL stored in an environment variable, and the environment variables are currently not available using the above suggested methods. It always renders as undefined.

**Comment by BrunoBernardino** [comment]
@BradStell is that on authentication fields? It should work if not, so let me know.

This is a bit tricky because of the event lifecycle when setting stuff up and showing it in Zaps.

It's possible, but involves some non-trivial changes and since it's only affecting authentication fields and there are workarounds, we're not prioritizing it.

I hope that makes sense!

**Comment by BradStell** [comment]
@BrunoBernardino It is not working for me.

This is my code:
![screen shot 2018-08-13 at 3 34 57 pm](https://user-images.githubusercontent.com/10966229/44056652-7926d52a-9f0e-11e8-90c9-d2917f554275.png)

And here is a look at my env var that is set
<img width="722" alt="screen shot 2018-08-13 at 3 35 42 pm" src="https://user-images.githubusercontent.com/10966229/44056687-937bd420-9f0e-11e8-9eb8-474cd0cf020d.png">

Do you mind sharing the changes that would make this possible?

**Comment by BrunoBernardino** [comment]
@BradStell it seems like that's on your authentication, so functions aren't working on those yet (that's why this ticket is open). For now you can simply hardcode it, I'm sorry.

**Comment by BradStell** [comment]
All good @BrunoBernardino , I miss-understood your last post. I thought you said there was a non trivial way to get it to work with authentication fields. I'll keep a watch on this ticket. Thanks

**Comment by BrunoBernardino** [comment]
Sorry, my bad! It's possible to fix this issue technically, but it's not trivial to implement, thus it hasn't been prioritized, that's what I meant!

**Comment by eibrahim** [comment]
Any updates?  I am struggling with getting this to work for helpText as well..

**Comment by xavdid** [comment]
I'm going to mark this as `wont-fix` given that it's been open a long time and we haven't prioritized it internally. 

Though `helpText` isn't evaluated at runtime, it _is_ evaluated at "push" time. You can run `VAR=123 zapier push` and the variable will be defined. It's not as easy to change on the fly, but has a similar effect. 

Thanks a bunch!
