### ISSUE TITLE
Field's choices aren't sorted

### ISSUE THREAD

**Issue by BrunoBernardino** [zapier/zapier-platform-cli#125]
### Actual Behavior

The `field.choices` is required to be an `Object`, which the [ECMAScript](http://www.ecma-international.org/ecma-262/8.0/index.html) defines as not having a predictable order in the properties.

This is causing a problem with choices being rendered with random sorting sometimes.

![](https://d1ax1i5f2y3x71.cloudfront.net/items/1N2v1r2b2t3T0J0G1f1B/Image%202017-08-23%20at%202.30.36%20AM.png?X-CloudApp-Visitor-Id=5750065e963b5636a49de305a744cf94&v=97656f2d)

### Expected Behavior

Choices should maintain sorting.

### Resources

- Slack convo: https://zapier-platform.slack.com/archives/C2S5DGF6G/p1503448271000081
- Private internal issue: https://github.com/zapier/zapier/issues/12998

**Comment by xavdid** [comment]
Cool, so I dug into this a bit. @bhberson is correct that as written, there's no way for `choices` to guarantee an order. 

There is a (bad) workaround though! Dynamic dropdowns return arrays of fields, so you can guarantee order: 

<img width="685" alt="screen shot 2017-08-24 at 4 03 51 pm" src="https://user-images.githubusercontent.com/1231935/29692692-34e13f84-88e6-11e7-8402-d01ed0ec4dd8.png">

<img width="690" alt="screen shot 2017-08-24 at 4 03 28 pm" src="https://user-images.githubusercontent.com/1231935/29692693-34f38be4-88e6-11e7-886e-c83053724ac2.png">

It's silly to have an entire hidden trigger just for 

```js
return [
        { id: 1, name: 'one' },
        { id: 2, name: 'two' },
        { id: 3, name: 'three' }
      ]
```

but it does work. So we can give that as a short term solution. 

I think the long term solution is to change [`FieldSchema.choices`](https://zapier.github.io/zapier-platform-schema/build/schema.html#fieldschema) to accept either an object (current, shorthand; if the order doesn't matter) or an array of `{id: string, label: string}`, to preserve order.

I'm not sure the cleanest way to make changes to schema (haven't actually modified that code before) but am happy taking ownership of that if we decide that's the best resolution. cc: @ZaneLyon

**Comment by xavdid** [comment]
this will go out in the next release!
