### ISSUE TITLE
core throws error in z.stashFile when files > 100 MB

### ISSUE THREAD

**Issue by BrunoBernardino** [zapier/zapier-platform-cli#126]
There are 3 issues here:

1. This file limit for `z.stashFile` isn't documented anywhere.

2. This limit might depend on the app, because it's really related to the 512 MB memory limit processes have.

3. These errors should be better exposed to the devs and tech support team.

Internal issue: https://github.com/zapier/zapier/issues/13018

**Comment by xavdid** [comment]
I believe this is fixed, per internal discussion.
