### ISSUE TITLE
Allow testing without making requests, i.e. mock z.request

### ISSUE THREAD

**Issue by BrunoBernardino** [zapier/zapier-platform-cli#129]
The title says it all.

It should be possible to allow devs to mock `z.request` and potentially other utilities (`z.stashFile` ?) from their own tests.

Slack convo: https://zapier-platform.slack.com/archives/C2S5DGF6G/p1503607083000230

**Comment by jpbernius** [comment]
Please put more priority on this! Mocking HTTP requests is very important for proper unit tests! Can you expose `z` on your `appTester` Object?
I would like to use something like [`fetch-mock`](http://www.wheresrhys.co.uk/fetch-mock) with my Zapier App.

**Comment by kevinansfield** [comment]
If anyone else runs across this whilst looking for ways to mock responses you can use [nock](https://github.com/node-nock/nock) or similar libraries without needing direct access to `z.request`

I've published an example of using `nock` in authentication tests here:
https://gist.github.com/kevinansfield/29ba88eeb1f2f1900b5df161721ea2ab

**Comment by xavdid** [comment]
Yep! Nock is the way to go. You can test with whatever values you'd like and the app itself never knows (and doesn't need to know whether) it's not getting a real reply back. 

I'll add a section on this to the docs and close the issue.
