### ISSUE TITLE
Determine uniqueness of a zap ( `object_id` )

### ISSUE THREAD

**Issue by drinchev** [zapier/zapier-platform-cli#132]
I want to be able to determine the uniqueness of a Zap.

Example

- User A creates Zap A, which sends requests to my API
- User B creates Zap B, which sends requests to my API
- User A creates Zap C, which sends requests to my API

In my API code I want to return specific results based on previous requests received by that Zap ( actually I want to implement a way to filter records that have been already sent - https://github.com/zapier/zapier-platform-cli/issues/131 ).

So far I found that there are some variables called `object_id` & `object_action` inside `request.input._zapier.event.logExtra` and this is what I'm doing : 

```
    beforeRequest : [
        ( request, z, bundle ) => {
            if ( request.input._zapier.event.logExtra ) {
                const logExtra = request.input._zapier.event.logExtra;
                request.headers["X-Zapier-Object-Id"] = logExtra.object_id;
                request.headers["X-Zapier-Object-Action"] = logExtra.object_action;
            }
            return request;
        }
    ]
```

According to my observations, `object_id` is unique for every Zap and my question is if that's true or not?

Thanks!

**Comment by benzapier** [comment]
That's a great question, however there are some edge-case problems that occur if/when your API/endpoints try to keep track of the records that have been returned to a consumer (like a Zap).  

One example: If a user goes into a Zap that's currently running, and re-runs the trigger test step, that will cause a poll that might accidentally consume "real" data that hasn't yet been polled by the Zap.

**Comment by bcooksey** [comment]
@drinchev Zapier will actually handle de-duplication on its own, you don't need to try to build it in. When we poll, we remember all the ids of the records we've seen, and only let new things through. It's actually preferable that your system does _not_ try to do anything fancy on your end, as that leads to state in two places and can make it a lot harder to debug errors.

If that satisfies the concern you had, let me know so I can close this issue.

**Comment by drinchev** [comment]
@bcooksey, @benzapier Thank you for your comments.

I'm actually really happy and satisfied how your de-duplication logic works.

What I'm worried is that, my response can have a magnitude of 50k+ or even more items ( database app with import CSV feature ). This makes it really hard for us as well, since we will have to provide every updated / created record each 5 minutes to each user that integrates with Zapier. The response size might go really big ( > 10 mb ), which I'm not sure how your client will handle. And anyway it's a total waste of resources to process on our side and on your side every time the same response.

Having the state on both sides, of course, is not a good solution, but it looks like a shortcut, because we are not able to provide webhooks triggers at this time.

Since I'm having my question answered, you can close this issue, of course.

**Comment by benzapier** [comment]
One possible workaround is to have your endpoint return just the record IDs, and then use [Dehydration](https://github.com/zapier/zapier-platform-cli#dehydration) within your integration, to return an array of requests that corresponds with each of the IDs. 

If the Zap has already "seen" all of the IDs, then there's no further action needed.  Otherwise, for each of the "new" IDs, the Zap will call the requests for each of the IDs (which your integration provided), and then will trigger the Zap with the data provided by each record.

That helps cut down on the amount of information that is needed during each polling cycle, and makes things work a bit more efficiently.

You can also reach us via [a public Slack channel](https://zapier-platform-slack.herokuapp.com) if you have any additional questions about getting things hooked up.

**Comment by bcooksey** [comment]
Something else we should mention upfront is that if there are 50k results in a single poll, that is gonna activate throttling on our side, so it may be worth pinging us in that channel @benzapier mentioned so we can find out more about this usecase and see if this is going to be a good fit for Zapier.
