### ISSUE TITLE
Doc rendered incorrectly for inputFormat

### ISSUE THREAD

**Issue by eliangcs** [zapier/zapier-platform-cli#134]
Head to https://zapier.github.io/zapier-platform-schema/build/schema.html and search for `inputFormat` to see this:

<img width="1014" alt="screen shot 2017-09-06 at 18 55 41" src="https://user-images.githubusercontent.com/740461/30108532-490466ea-9335-11e7-9b31-feda1a12be43.png">

Seems like GitHub Pages somehow replaced `{{input}}` with an empty string. This is [how it should look like](https://github.com/zapier/zapier-platform-schema/blob/b4bbb50aa491a93f915808ea11c9755cbf2d3812/docs/build/schema.md#properties-12).

**Comment by eliangcs** [comment]
Related: https://github.com/jekyll/jekyll/issues/6217

**Comment by xavdid** [comment]
@eliangcs I believe this fixed itself? Feel free to close if that's the case

![](https://cdn.zapier.com/storage/photos/ff515ecc324f048c8a9cc98063e69409.png)

**Comment by eliangcs** [comment]
Nope, https://zapier.github.io/zapier-platform-schema/build/schema.html still has this issue.

**Comment by xavdid** [comment]
oh, I was looking at the wrong page. sorry about that!

**Comment by eliangcs** [comment]
Fixed by zapier/zapier-platform-schema#35.
