### ISSUE TITLE
Create Zapier CLI app to allow automations around app actions

### ISSUE THREAD

**Issue by BrunoBernardino** [zapier/zapier-platform-cli#135]
An initial plan would be something like:

### Auth

- CLI App ID? Key? Choose from your own apps? Any owned app?

### Triggers

- New version
- New version update

- Zapier convo: https://zapier-platform.slack.com/archives/C2S5DGF6G/p1504788550000245

**Comment by xavdid** [comment]
This is cool but is unlikely to happen outside of a hackathon or something.
