### ISSUE TITLE
Expose request timeouts before Lambda times out

### ISSUE THREAD

**Issue by FokkeZB** [zapier/zapier-platform-cli#136]
When a request times out, the error will be that lambda times out (which of course is true):

![](https://cdn.zapier.com/storage/photos/9053fb529236a4ce6acdc05c51e78b79.png)

We could set a default [timeout](https://www.npmjs.com/package/fetch#options) of e.g. 25s, but what if you are doing pre-request stuff that takes a few seconds and then start the request 5+ seconds in?

See https://github.com/zapier/zapier/pull/13191#issuecomment-327821751

**Comment by xavdid** [comment]
the internal version of this issue was closed, so i'll assume this is resolved.
