### ISSUE TITLE
Expose the zap in the bundle during the performSubscribe function

### ISSUE THREAD

**Issue by rymndhng** [zapier/zapier-platform-cli#137]
When we're registering a RestHook (using `performSubscribe`), we would like to know the zap's `id` on creation.

The use case is for our system to store an identifier for a zap so we can combine data from our API with Zapier's API (particularly the `/zaps` endpoint) to build a richer user experience.

**Comment by bcooksey** [comment]
@rymndhng Can you elaborate a bit on how the Zap ID helps. Is this so you can tie the webhook URL you get from Zapier during the subscribe process with a Zap that comes back from the `/zaps` endpoint? Excited to know what the richer experience is.

**Comment by rymndhng** [comment]
We're trying to build a UI that allows us to show how the webhooks is working End-to-End. We are having trouble joining data from our system & zapier's API. 

When we query the `/zaps` API, we get a list of zaps back. We currently have no way of reliably joining the list of zaps from that endpoint with the list of zaps from our system.

**Comment by ibolmo** [comment]
This shipped today. You can find the zap id in the `bundle.meta.zap` object available in the `performSubscribe` as well as the `performUnsubscribe` methods.

**Comment by ecdeveloper** [comment]
Having zap id is very convenient. But I was wondering if there's also a way to get the Zap's name during `performSubscribe`?

**Comment by ibolmo** [comment]
@ecdeveloper I realize this doesn't immediately solve your problems, but you could use the Partner API to get this information: https://zapier.com/developer/documentation/v2/partner-api/

If you're able to, would you mind sharing with us the use case of having the name of the Zap?

**Comment by ecdeveloper** [comment]
Using the partner API seems like an overhead to me, tbh. But if thats the only way, well, I guess I have no choice haha. 

My use case is the following - users have some entities within my platform/service. In certain cases, those entities can emit/trigger events. User can choose what should happen when an event triggers. For example they can make those entities send out an email, or send a slack message, or trigger a zap. I'd like my users to be able to have multiple Zaps, which are available within my platform (for instance when they want different entities to trigger different zaps). It would be really convenient for a user to see those Zaps along with their names (just like they see a list of email addresses they can send the email to, or a list of slack teams / slack channels they can send a message to). 

Hopefully it makes sense.
