### ISSUE TITLE
InputField's `computed` doesn't do what is documented

### ISSUE THREAD

**Issue by rymndhng** [zapier/zapier-platform-cli#138]
Are there some examples/demos of this in use. We wanted to make an inputField computed and noticed:

- it's not apparent how to fill this data
- the field is not hidden in the UI
- when a zap is copied, the computed field is sent as a custom field rather than re-computed.

**Comment by BrunoBernardino** [comment]
@rymndhng this should be used only for auth fields (for you to save something from OAuth or Session Auth, for example, without having to ask the customer about it). We're working on making it hidden in the UI for that situation, and will add some examples in the readme soon as well.

**Comment by rymndhng** [comment]
@BrunoBernardino thanks for the clarification. 👍
