### ISSUE TITLE
The command `zapier build` omits non-code data files from `build.zip`

### ISSUE THREAD

**Issue by benzapier** [zapier/zapier-platform-cli#139]
The command `zapier build` starts with the `index.js` file, and adds all referenced files/dependencies/modules into the final `build.zip`

Thus, any non-code "important data/config" files needed by your integration (or modules) will be missing when the code is pushed up to Zapier's systems - such as any/all `json`, `xml`, `yml`, or other text/data file(s).  Node modules like `xml2js` also trip over this issue, because it requires/needs a configuration file that's contained within its `node_modules` directory structure.

The current workaround is to make a script on your local dev environment, that performs the following steps:
  * `zapier build`  - creates the `build.zip` file
  * Shell scripting commands to `unzip` the `build.zip` into a temporary directory
  * Shell scripting commands that copy over the necessary data/config files into that temporary directory
  * Shell scripting commands to `zip` the files in that temporary directory, and create a new version of `build.zip`
  * `zapier upload` to send that updated `build.zip` to the Zapier system.

The most likely solution will be adding some kind of Zapier-app-config file, which includes the paths/names of any additional (non-code) files to be included when building the zip file.  Ideally, this should support file globbing, but may run into limitations on Windows file systems.

**Comment by BrunoBernardino** [comment]
I've tried a solution at #158 because I needed to include a file in the checks (for the interpreter), but was hitting a problem and I didn't really need that solution, so I just left it there and you're welcome to look into it, or I will sometime in the future.

**Comment by BrunoBernardino** [comment]
Tracking in linked PR.
