### ISSUE TITLE
Why does `z.request` work with an object for `body` ?

### ISSUE THREAD

**Issue by FokkeZB** [zapier/zapier-platform-cli#143]
At https://github.com/zapier/zapier-platform-cli#http-request-options we repeat ​https://www.npmjs.com/package/node-fetch#options which says `body` "can be a string, buffer, or readable stream":

![](https://cdn.zapier.com/storage/photos/54543d3914608752a815ba8b59c80ec9.png)

Yet in examples like https://github.com/zapier/zapier-platform-example-app-oauth2/blob/master/authentication.js#L2-L13 we set it to an object.

While https://github.com/bitinn/node-fetch/blob/master/src/body.js#L48 would convert that into a useless `[Object object]` string.

So the question is; why does this work? And assume it works, we should document how/why.

/cc @BrunoBernardino

**Comment by bryanhelmig** [comment]
We gave some sugar middleware https://github.com/zapier/zapier-platform-core/blob/master/src/http-middlewares/before/prepare-request.js.

**Comment by FokkeZB** [comment]
Thanks @bryanhelmig!

PR: https://github.com/zapier/zapier-platform-cli/pull/145
