### ISSUE TITLE
Global Access to z Object

### ISSUE THREAD

**Issue by armordog** [zapier/zapier-platform-cli#147]
I'd like to wrap my actual request preparation and response parsing in a separate function (something like `const makeApiRequest = import('./api/makeRequest');`)

Currently, I need to pass `z` into my function just to get the `z.request` method.

1) Is there a proper way to access `z` (or `z.request`) globally?

2) Is it safe to just capture `z` once and re-use it elsewhere?

**Comment by bryanhelmig** [comment]
1. No -- `z` is generated on the fly with lots of specialized context for the specific trigger/action/etc.
2. No -- don't store `z` and reuse it.

Passing as an argument is the current best practice!
