### ISSUE TITLE
Create dynamic dropdown from resource, without creating a new trigger.

### ISSUE THREAD

**Issue by theonastos** [zapier/zapier-platform-cli#148]
I need to generate a dynamic dropdown as a prerequisite field in one of my triggers. The only possible way to generate this, is by using a resource and using its list element.
The list element though creates an unwanted trigger. Is there not a way around this?

**Comment by bryanhelmig** [comment]
You can mark the trigger as hidden -- that way our system still has all the relationships it needs to operate but users cannot use it as a trigger!

https://github.com/zapier/zapier-platform-schema/blob/9234d1d04f9722856a61a4a5dd8ad12a6be7bf49/lib/schemas/BasicDisplaySchema.js#L41
