### ISSUE TITLE
cli fails when not in root project dir

### ISSUE THREAD

**Issue by codekirei** [zapier/zapier-platform-cli#151]
![](https://cdn.zapier.com/storage/photos/6adb1f73ae9cf3d1fcdeb4c9f9062c2a.png)

![](https://cdn.zapier.com/storage/photos/46c13643542fb97ebec270037a093367.png)

We could use something like [pkg-dir](https://www.npmjs.com/package/pkg-dir) to traverse up the fs tree for the nearest `package.json`.

**Comment by xavdid** [comment]
I think pkg-dir would totally solve this problem, but it doesn't seem like it's much of an issue.
