### ISSUE TITLE
zapier env reports Error: Cannot parse time: NaN

### ISSUE THREAD

**Issue by bradleyayers** [zapier/zapier-platform-cli#156]
When I use `zapier env …`, I get an error. When using `--debug`, the output is:

```
$ zapier --debug env 1.0.0 BASE_URL https://<snip>.ngrok.io
>> GET https://zapier.com/api/platform/cli/check
<< 200
<< {"success": true}

>> GET https://zapier.com/api/platform/cli/apps/<snip>
<< 200
<< <snip>

Preparing to set environment BASE_URL for your 1.0.0 <snip>.

  Setting BASE_URL to "https://<snip>.ngrok.io" ⠃>> PUT https://zapier.com/api/platform/cli/apps/<snip>/environment/BASE_URL
>> <snip>
<< 200
<< {"key": "BASE_URL", "app_version": "1.0.0", <snip>}

⠃ done!

Environment updated! Try viewing it with `zapier env 1.0.0`.

Error: Cannot parse time: NaN
    at toUnixTimestamp (fs.js:1196:9)
    at Object.fs.utimesSync (fs.js:1218:11)
    at /usr/local/lib/node_modules/zapier-platform-cli/lib/commands/env.js:33:10
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

Error!
```

**Comment by xavdid** [comment]
That's very strange! that hasn't been touched in a while (over a year) so it's weird that you're seeing it break. 

Can you give us versions of the node + cli (`zapier -v`) and what operating system?

**Comment by bradleyayers** [comment]
> Can you give us versions of the node + cli (zapier -v) and what operating system?

```
$ zapier  -v
zapier-platform-cli/3.2.0
node/v8.4.0
$ uname -a
Darwin brad.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
```

**Comment by xavdid** [comment]
Got it! 

I was able to reproduce on `8.4.0`, but it works as expected on node `6.10.2`, which is the currently supported version of node. I'm not sure what's causing the bug, but i'll close for now and we'll revisit when 8.x is LTS. How does that sound?

**Comment by bradleyayers** [comment]
I expected 6.10.2 to be the required version for the _deployment_ environment, it's surprising to me that it's also the required version for the _development_ environment where the CLI tool is used. It's not necessarily a bad thing, it's just surprising. (Though I can imagine it might be useful for the validation command).

It'd be awesome if there was a check in the CLI when it begins executing to ensure that the correct version of node is being used, and to bail out with a clear error if that's not the case. With 6.x becoming more and more ancient, it's probably going to be more and more common that developers try to run it with a recent version of node.

Happy for this to be closed though…

**Comment by xavdid** [comment]
For sure, we could be more clear. As for 6.x, we're restricted by the [latest version](https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html) available on lambda. the `zapier test` and `zapier validate` all throw errors if they're not being run in `6.10.x`. 

That said, most other versions of the CLI have worked on forward versions of node. The fact that this doesn't is totally a bug and will need to be fixed, it's just not a priority until 8.x is ready for prime time.
