### ISSUE TITLE
Error on Zap: "authentication failed: Handler 'handler' missing on module 'zapierwrapper'"

### ISSUE THREAD

**Issue by BrunoBernardino** [zapier/zapier-platform-cli#157]
This is caused because the `build.zip` file that's uploaded is empty, even though locally, the file is fine.

We're still investigating what the issue is, but doesn't seem to be related to `3.2.0` as reverting both `zapier-platform-core` and `zapier-platform-cli` to `3.1.0` isn't fixing the problem.

**Comment by reganstarr** [comment]
## Affected users:

- https://secure.helpscout.net/conversation/446824475/684539/

**Comment by BrunoBernardino** [comment]
Alright, just confirmed the dependency was a child of a child of `archiver`, https://github.com/archiverjs/node-compress-commons/releases.

I'm going to ship a fix forcing that specific child (and a few others I found to be different) to be on 1.2.0 instead of 1.2.1
