### ISSUE TITLE
Encode Spaces as "+" rather than "%20", for form-encoded requests.

### ISSUE THREAD

**Issue by condad** [zapier/zapier-platform-cli#161]
Many legacy systems expect spaces to be encoded with a "+", rather than "%20".

To reproduce this issue, submit the same form-encoded request (with spaces) with CLI Zapier app and with a command line tool like cURL or HTTPie. Afterwards, compare the request bodies to see the difference.

**Comment by BrunoBernardino** [comment]
Thanks for this @condad, and I'm sorry for the late reply here.

We'll release a new (probably backwards-breaking) version fixing this, but for now, an alternative is to send the body as a string, which we won't tamper with:

```js
z.request({
  url: 'https://...',
  method: 'POST',
  headers: {
    'content-type': 'application/x-www-form-urlencoded'
  },
  body: Object.keys(bundle.inputData).map((key) => `${key}=${encodeURIComponent(bundle.inputData[key]).replace(/%20/g, '+')}`).join('&')
});
```
