### ISSUE TITLE
"File is too big" message isn't self-supportable

### ISSUE THREAD

**Issue by FokkeZB** [zapier/zapier-platform-cli#165]
When the ZIP file is over 50 MB we yell:

```
Error! "https://zapier.com/api/platform/cli/apps/122/versions/1.0.0" returned "403" saying "File is too big."
```

It would be good to make this self-supportable by explaining what file is too big for what, why and how to deal with it. For example:

```
Error! Your app zipped is 100 MB which exceeds the 6 MB we allow. Please slim down your app and dependencies before trying again.
```

**Update:** It's not 50 MB but 6 MB. Lambda has a 50 MB limit, but we limit to 6 in https://github.com/zapier/zapier/blob/f88406df19834633cad9070468bff49a2cfd0027/developer_cli/utils.py#L121

**Comment by hickeroar** [comment]
Somewhat related, I would personally like to know why, when I was using version 3.2.1 of the platform core I could build using `--disable-dependency-detection` (which is basically required if you want your app to actually work when you have ANY dependencies) and it would upload fine. I "upgrade" to 4.1.0 and my file is now somehow too large. 30 seconds ago on 3.2.1 it wasn't.

**Comment by FokkeZB** [comment]
@hickeroar what is the ID of your CLI app? We'd love to take a look!

**Comment by hickeroar** [comment]
The ID is 512. It's open source, so you can see it here as well:
https://github.com/savoryinstitute/classy-zapier

I did confirm, if I use `--disable-dependency-detection` on version 3.2.1 the zip is around 4.7MB. On 4.1.0 it's about 27MB. I'm not sure what is causing the difference in file size, but for now I swapped back to 3.2.1 and it's working fine.

Thanks for checking into it. :)

**Comment by eliangcs** [comment]
@hickeroar I'm able to reproduce the issue. I found that we accidentally packed an unnecessary file into our zapier-platform-core 4.1.0 package. We'll ship a new version addressing this issue soon. Will keep you posted here once it's released. Thanks for reporting the issue!

**Comment by eliangcs** [comment]
@hickeroar We just released 4.2.1, which should fix the problem. Could you confirm if it's fixed? Thanks!

**Comment by hickeroar** [comment]
4.2.1 still seems to be producing a 23MB zip file for me. :-(

**Comment by eliangcs** [comment]
@hickeroar sorry for the hassle. We released another build 4.2.3. Could you try again?

**Comment by hickeroar** [comment]
Looks like that build came out at just over 4MB, so it looks good to go. Thanks!

**Comment by R3dC0d3** [comment]
Hi there,
I'm also getting the same error when running zapier push with --disable-dependency-detection.
I'm using v8.1.
Is there a way to fix this?

**Comment by xavdid** [comment]
@R3dC0d3 can you file a new issue? this one was resolved and mistakenly left unclosed. Thanks!
