### ISSUE TITLE
Scopes should support '+' rather than encoding into '%2B'

### ISSUE THREAD

**Issue by bhberson** [zapier/zapier-platform-cli#176]
Currently when including '+' delimited scopes, Zapier CLI platform encodes them with '%2B' . The Plus signs should be acceptable so that it creates an authorization URL like so: `https://{{app}}.com/oauth/authorize?client_id={{client_id}}&redirect_uri=https%3A%2F%2Fzapier.com%2Fdashboard%2Fauth%2Foauth%2Freturn%2F{{App}}CLIAPI%2F&response_type=code&scope=public+read_user+write_user&state={{state}}`

Many apps will think the %2B delimited scopes are malformed or invalid.

**Comment by BrunoBernardino** [comment]
This would've been fixed by https://github.com/zapier/zapier-platform-core/pull/52 which was included in `4.0.0`. Could you check if that isn't the case?
