### ISSUE TITLE
zapier push fails with "Cannot find module 'supports-color'"

### ISSUE THREAD

**Issue by aymericbouzy** [zapier/zapier-platform-cli#189]
When running `zapier push`, I get the following error : 
```
Preparing to build and upload your app.

  Copying project to temp directory ⠃ done!
  Installing project dependencies ⠃ done!
  Applying entry point file ⠃ done!
  Building app definition.json ⠃ done!
  Validating project ⠃ done!
  Zipping project and dependencies ⠰events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'supports-color' from '/private/var/folders/dw/d_f_yf1x5zz2fm1rtkpxzmw00000gn/T/zapier-19a7602e/node_modules/debug/src'
    at /Users/aymericbouzy/.nvm/versions/node/v6.10.2/lib/node_modules/zapier-platform-cli/node_modules/resolve/lib/async.js:48:31
    at processDirs (/Users/aymericbouzy/.nvm/versions/node/v6.10.2/lib/node_modules/zapier-platform-cli/node_modules/resolve/lib/async.js:182:39)
    at ondir (/Users/aymericbouzy/.nvm/versions/node/v6.10.2/lib/node_modules/zapier-platform-cli/node_modules/resolve/lib/async.js:197:13)
    at load (/Users/aymericbouzy/.nvm/versions/node/v6.10.2/lib/node_modules/zapier-platform-cli/node_modules/resolve/lib/async.js:80:43)
    at onex (/Users/aymericbouzy/.nvm/versions/node/v6.10.2/lib/node_modules/zapier-platform-cli/node_modules/resolve/lib/async.js:105:17)
    at /Users/aymericbouzy/.nvm/versions/node/v6.10.2/lib/node_modules/zapier-platform-cli/node_modules/resolve/lib/async.js:26:73
    at FSReqWrap.oncomplete (fs.js:123:15)
```

Previously it was working fine ...

**Comment by aymericbouzy** [comment]
Output of `zapier push --debug` : 

```
Preparing to build and upload your app.

>> GET https://zapier.com/api/platform/cli/check
<< 200
<< {"success": true}

  Copying project to temp directory ⠃ done!
  Installing project dependencies ⠘

Running npm install --production command in /private/var/folders/dw/d_f_yf1x5zz2fm1rtkpxzmw00000gn/T/zapier-c0fec6e8:

⠉gofer-zapier@1.0.0 /private/var/folders/dw/d_f_yf1x5zz2fm1rtkpxzmw00000gn/T/zapier-c0fec6e8
├─┬ axios@0.17.1 
│ ├─┬ follow-redirects@1.2.6 
│ │ └─┬ debug@3.1.0 
│ │   └── ms@2.0.0 
│ └── is-buffer@1.1.6 
├─┬ graphql-request@1.4.0 
│ └─┬ cross-fetch@0.0.8 
│   ├── node-fetch@1.7.3 
│   └── whatwg-fetch@2.0.3 
├── moment@2.19.2 
└─┬ zapier-platform-core@3.3.0 
  ├── bluebird@3.5.0 
  ├── content-disposition@0.5.2 
  ├── dotenv@4.0.0 
  ├─┬ form-data@2.2.0 
  │ ├── asynckit@0.4.0 
  │ ├─┬ combined-stream@1.0.5 
  │ │ └── delayed-stream@1.0.0 
  │ └─┬ mime-types@2.1.17 
  │   └── mime-db@1.30.0 
  ├── lodash@4.17.4 
  ├─┬ node-fetch@1.7.1 
  │ ├─┬ encoding@0.1.12 
  │ │ └── iconv-lite@0.4.19 
  │ └── is-stream@1.1.0 
  └─┬ zapier-platform-schema@3.3.0 
    └── jsonschema@1.1.1 


⠃ done!
  Applying entry point file ⠃ done!
  Building app definition.json ⠃ done!
  Validating project ⠤>> POST https://zapier.com/api/platform/cli/style-check
>> {"version":"1.0.0","platformVersion":"3.3.0","beforeRequest":[],"afterResponse":[],"resources":{},"triggers":{"contractValidation":{"key":"contractValidation","noun":"Contract Validation","display":{"label":"New Contract Validation","description":"Trigger when a contract is signed by a worker."},"operation":{"perform":"$func$2$t$"}}},"searches":{},"creates":{},"searchOrCreates":{},"zip_file":"raw zip removed in logs"}
<< 200
<< {"errors": {}, "warnings": {}}

⠃ done!
  Zipping project and dependencies ⠉events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'supports-color' from '/private/var/folders/dw/d_f_yf1x5zz2fm1rtkpxzmw00000gn/T/zapier-c0fec6e8/node_modules/debug/src'
    at /Users/aymericbouzy/.nvm/versions/node/v6.10.2/lib/node_modules/zapier-platform-cli/node_modules/resolve/lib/async.js:48:31
    at processDirs (/Users/aymericbouzy/.nvm/versions/node/v6.10.2/lib/node_modules/zapier-platform-cli/node_modules/resolve/lib/async.js:182:39)
    at ondir (/Users/aymericbouzy/.nvm/versions/node/v6.10.2/lib/node_modules/zapier-platform-cli/node_modules/resolve/lib/async.js:197:13)
    at load (/Users/aymericbouzy/.nvm/versions/node/v6.10.2/lib/node_modules/zapier-platform-cli/node_modules/resolve/lib/async.js:80:43)
    at onex (/Users/aymericbouzy/.nvm/versions/node/v6.10.2/lib/node_modules/zapier-platform-cli/node_modules/resolve/lib/async.js:105:17)
    at /Users/aymericbouzy/.nvm/versions/node/v6.10.2/lib/node_modules/zapier-platform-cli/node_modules/resolve/lib/async.js:26:73
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by bryanhelmig** [comment]
Can you share your `package.json`? My naive guess would be to make sure `supports-color` is listed as a dependency in there.

**Comment by aymericbouzy** [comment]
Indeed adding `supports-color` fixes it 🎉 
Isn't it one of zapier's dependencies ? Error message doesn't make it clear, but it doesn't look like one of my dependencies ...

**Comment by BrunoBernardino** [comment]
It doesn't seem to be a dependency from CLI: https://github.com/zapier/zapier-platform-cli/blob/master/package.json#L30 nor Core: https://github.com/zapier/zapier-platform-core/blob/master/package.json#L28 so I'd lean towards it being a dependency on your app.

Would you mind confirming if that's the case?

**Comment by aymericbouzy** [comment]
It is a nested dependency of one of my dev dependencies. Everything works fine until I run `zapier push`. I'm not exactly sure why your code fails, but it is quite puzzling at first. Fixing it by adding the nested dependency looks to me like a quick and dirty fix : what if the dependency stops depending on it? What if they need another version?

So the question remains : why is your code failing in the first place?

Here is my current `package.json`:

```json
{
  "name": "gofer-zapier",
  "version": "1.0.0",
  "description": "Integration of Zapier with Gofer API",
  "author": "Aymeric Bouzy <aymeric@gofer.fr>",
  "private": true,
  "main": "dist/index.js",
  "scripts": {
    "test": "jest --config jest.config.json",
    "test-watch": "jest --watch --notify -o --config jest.config.json",
    "build": "rm -rf dist && babel src --out-dir dist",
    "deploy": "yarn build && zapier test && zapier push"
  },
  "engines": {
    "node": "6.10.2",
    "npm": ">=3.10.10"
  },
  "dependencies": {
    "axios": "^0.17.1",
    "graphql-request": "^1.4.0",
    "moment": "^2.19.2",
    "supports-color": "^5.0.0",
    "zapier-platform-core": "4.0.0"
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-eslint": "^8.0.2",
    "babel-plugin-root-import": "^5.1.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-stage-3": "^6.24.1",
    "eslint": "^4.11.0",
    "eslint-config-prettier": "^2.8.0",
    "eslint-plugin-prettier": "^2.3.1",
    "jest": "^21.2.1",
    "mockdate": "^2.0.2",
    "prettier": "^1.8.2"
  }
}
```

**Comment by BrunoBernardino** [comment]
We would need to look a the code. Maybe something in your `devDependencies` should _really_ be in `dependencies`, because we `npm install --production` for the `zapier build` (`zapier push` runs that first).

Does that make sense? Do you know which package is requiring it?

**Comment by aymericbouzy** [comment]
running `yarn why supports-color` indicates `chalk` depends on it, itself depending on:

```
- babel-eslint#@babel/code-frame
- eslint
- jest#jest-cli
```

My understanding of each of these packages is that they should be in `devDependencies`...

What do you mean by "running the code"? Is there a command for running the code the same way zapier does it? 

Until now, I've only ever run tests, which obviously depend on dev dependencies.

**Comment by BrunoBernardino** [comment]
Oh, sorry! Yeah, I was thinking running the tests, but indeed you need at least `jest` for that. 🤦‍♂️ 

How are you using babel? Are you building with a command, or running it in "runtime"?

It's also possible `browserify` gets confused when it's looking for all existing dependencies.

I'd try moving each dev dependency into a dependency (removing supports-color) and seeing which one would "pass". At least it should make it more maintainable.

Does that make sense?

**Comment by aymericbouzy** [comment]
As you can see in the `"scripts"` part of my `package.json`, I have a `"build"` script that compiles all files in the `src` folder to the `dist` folder using babel. This is the only place I use babel. In fact, I only ever use the `"deploy"` script : it compiles with babel, then runs the tests, and if all tests pass, it runs `zapier push`.

This is the only way I'm using babel. No runtime.

So I guess I'll try moving `jest` to my `dependencies`, but it looks weird to me ...

**Comment by aymericbouzy** [comment]
I confirm adding `jest` to my dependencies (after having remove `supports-color`) solves the issue. Will you consider documenting that all test related dependencies should be added as dependencies and not as devDependencies?

**Comment by BrunoBernardino** [comment]
The truth is that's not necessary for `mocha`, for example (so that information in the documentation could cause confusion), so it seems related to `jest` and I agree it's really strange.

We do have this information in https://zapier.github.io/zapier-platform-cli/#using-npm-modules:

> Note: If your package isn't being pushed correctly (IE: you get "Error: Cannot find module 'whatever'" in production), try adding the `--disable-dependency-detection` flag to `zapier push`.

Does that work for you (while keeping `jest` in devDependencies?)

Also, could you tell me what's your app id (look in `.zapierapprc`)? I'll look at the built code and try to understand if it's something with `browserify` ()

We have a babel example that doesn't need that, but babel is in its dependencies: https://github.com/zapier/zapier-platform-example-app-babel/blob/master/package.json

**Comment by aymericbouzy** [comment]
Running `zapier push --disable-dependency-detection` gives exactly the same result as `zapier push`.

My app id is 1654.

Off topic : why are you using browserify? Can't you run the code server-side? Is it for security reasons that you run the code client-side? why do you use browserify rather than any other bundler?

**Comment by BrunoBernardino** [comment]
Hi @aymericbouzy indeed in the built code I can't see any requirement of `jest` that would cause that.

I'm not sure how productive it is to chase this, unless other people start running into it, but I'd have to look into your original, unbuilt code to continue debugging.

As for `browserify`, we're using it only to guarantee there aren't any missing dependencies on `zapier build`, and as a simple way to copy only "needed" files (a simple way to reduce the files added to `build.zip`).

**Comment by aymericbouzy** [comment]
let's leave it there unless someone else runs into the same issue :)
Thanks for your help and dedication!

**Comment by z4m0** [comment]
I'm getting the same error. It was working fine and no dependences were added.  
npm install --save supports-color fixes the error but makes the file too big and I can't push it.

**Comment by BrunoBernardino** [comment]
Yep, confirmed that's causing it because `supports-color` isn't really a dependency, but has a `require()`, which makes `browserify` freak out. I'm adding an exclusion for that package. If we see this happening more frequently, we'll try other alternatives to `browserify` there.

Thanks for your patience on this guys (and @z4m0 for the pointer), we will be shipping a fix soon.
