### ISSUE TITLE
How do you set your app icon?

### ISSUE THREAD

**Issue by mrozbarry** [zapier/zapier-platform-cli#190]
Every public app has icons and logos, but when I'm testing my app, I see no way to upload/add an icon.

**Comment by BrunoBernardino** [comment]
Hi @mrozbarry, thanks for reaching out (sorry about the late reply here, holidays)!

You can only do it through the UI for now. You should be able to login to Zapier and go to https://zapier.com/developer/ to see your app listed. There you can edit the description and image.

Let me know if that works, or if you've got any questions!
