### ISSUE TITLE
Correction in tutorial section of the doc.

### ISSUE THREAD

**Issue by kola-er** [zapier/zapier-platform-cli#20]
Considering that https://github.com/zapier/zapier-platform-cli/pull/3 was closed, I think raising an issue would do.

Here https://github.com/zapier/zapier-platform-cli/blob/master/README-source.md#adding-authentication, I think `required` parameter is required in `{key: 'apiKey', type: 'string'}` for the input field to be displayed while trying to connect a new account.

**Comment by BrunoBernardino** [comment]
<img width="642" alt="screen shot 2017-03-23 at 15 21 14" src="https://cloud.githubusercontent.com/assets/1239616/24255048/5f372ff6-0fdc-11e7-9c0b-2bd632b27d6b.png">

This had been fixed meanwhile!
