### ISSUE TITLE
Zapier Convert doesn't escape single quotes in labels

### ISSUE THREAD

**Issue by FokkeZB** [zapier/zapier-platform-cli#217]
User runs `zapier convert 71623 "dir"` and ends up with this syntax error in the generated code:

```
Error!Unexpected token, expected "," (43:26)
41 | {
42 | key:'groupIDs',
> 43 | label:'Group ID's',
| ^
44 | helpText:'List of Group ID\'s will be converted to list of Group Names.',
45 | type:'integer',
46 | required:true
```

As you can see the single quote is not escaped.

**Comment by eliangcs** [comment]
What's the version of CLI does the user use? I ran it with 4.2.3 and didn't see this error.

**Comment by FokkeZB** [comment]
@eliangcs I've asked:
https://secure.helpscout.net/conversation/492844068/749906/?folderId=20363

**Comment by FokkeZB** [comment]
@eliangcs the user is on 4.2.3 with node v6.10.2. I cannot reproduce it either and get:

```
      {
        key: 'groupIDs',
        label: 'Group IDs',
        helpText: "List of Group ID's will be converted to list of Group Names.",
        type: 'integer',
        required: true
      }
```
