### ISSUE TITLE
Bug: Password-type auth-fields not rendered as such

### ISSUE THREAD

**Issue by cvanderkolk** [zapier/zapier-platform-cli#220]
## Current Behavior

Fields marked as `password` aren't censored like a traditional login form when using a Custom Auth scheme:

![](https://cdn.zapier.com/storage/photos/33a2300a476a11decdcf93c497621ec3.png)

## Expected Behavior

Devs would like to be able to censor an auth field in the Authorization connection window, particularly for a `password` field while using a Custom Auth scheme.

This could be accomplished by adding a boolean `censored` property to our [Authentication field schema](https://zapier.github.io/zapier-platform-schema/build/schema.html#authenticationschema) that devs could mark as `True` to toggle censoring behavior on the front end.

Another possible solution is to automatically censor any field containing the word `password`.

**Comment by FokkeZB** [comment]
Weird, I think we should already censor all auth fields:

https://github.com/zapier/zapier-platform-core/blob/1c86aa9eaec1f4acbba4ef3e447d0ec271809a1b/src/tools/create-logger.js#L67

Perhaps the password value was less than 6 chars @cvanderkolk ?

**Comment by cvanderkolk** [comment]
@FokkeZB To clarify, I didn't mean censoring in the logs. I meant censoring fields in the Authorization window when people go to connect their account. I adjusted my original feature request to reflect that!

**Comment by FokkeZB** [comment]
I'm probably slow after being OOO for a week, but could you add a screenshot exemplifying the issue perhaps? Still don't fully get it :)

**Comment by cvanderkolk** [comment]
@FokkeZB Blame it on me - I should have shared this in the original issue! Here's the shot that the user shared: ![](https://cdn.zapier.com/storage/photos/4fb8756100f35435c2afc5ebc12e9f06.png)

They were hoping there was a way for the password to be censored when entering it, like a traditional password field in a form.

**Comment by FokkeZB** [comment]
If that _Password_ field has its `type` set to `password` then I'd say this is a bug. The front-end should render those as `<input type="password" />` which would mask the input.

**Comment by xavdid** [comment]
@cvanderkolk I couldn't reproduce this-

![](https://cdn.zapier.com/storage/photos/1e383e6ebf2484a401493624e08ac515.png)

generated from

```js
authentication: {
    type: 'custom',
    test: () => {
      return true
    },
    fields: [
      { key: 'un', required: true },
      { key: 'pw', required: true, type: 'password' }
    ]
  }
```

note the `type: 'password'`, which marks the field as censored. Was there a ticket that filed this? were they missing that?

**Comment by cvanderkolk** [comment]
@xavdid that's exactly what was happening 🤦‍♂️ I should have dug a little further here before making an issue - sorry for sending you down a rabbit hole here! I'm going to follow up with the user and close this outl
