### ISSUE TITLE
Action ordering

### ISSUE THREAD

**Issue by jr-k** [zapier/zapier-platform-cli#221]
Hello,

I've some problems with sorting my Actions (see here: https://i.imgur.com/apMl3F2.png), I tried order:[integer] (see here: https://i.imgur.com/1hilyOr.png) but that doesn't work (and that solution is marked as deprecated in the zapier platform schema).

I also tried to change my key ("a","b","c","d" for each Actions) but no sort seems to be applied.

I'm using CLI and NOT the web builder.

Can you help me on this please ?

Thanks !

**Comment by xavdid** [comment]
Copying Zane's answer: 

Actions will get ordered by the platform automatically based on which ones actually get used most in Zaps. This will appear kind of arbitrary until you get more Zapier users using your app, but we've found it creates the best user experience for most folks.
