### ISSUE TITLE
Support for Google Cloud Datastore cursors for paging

### ISSUE THREAD

**Issue by bmichelich** [zapier/zapier-platform-cli#235]
The zapier platform paging support assumes a SQL backbacked api or similar (page * offset) with a `page` parameter.

Google Cloud Datastore provides a `cursor` to enable paging with large result sets.
It is common for API's using GCD to return the cursor in the json response to enable api paging.

https://cloud.google.com/datastore/docs/concepts/queries#cursors_limits_and_offsets

The `cursor` value could be detected and made available for dynamic menu's similar to how paging works now with `bundle.meta.page` https://github.com/zapier/zapier-platform-cli#paging

Not sure this makes sense as a feature request, making some assumptions about that the platform is doing.

**Comment by xavdid** [comment]
Good news! This was released as part of `6.1.0`. There are docs about it [here](https://github.com/zapier/zapier-platform-cli#paging). ​Let me know if you've got any other questions!
