### ISSUE TITLE
Commands that allow a "--format" argument return invalid JSON

### ISSUE THREAD

**Issue by devert** [zapier/zapier-platform-cli#247]
The ability to define the display format  of "raw" or "json", for certain commands, has diminished value because there is always a context line at the beginning of what is returned, which makes it technically invalid JSON data. It would be nice to be able to parse and filter this data with tools like [jq](https://stedolan.github.io/jq/) to inform other commands, in for instance a CI pipeline, without having to strip that first line out of the returned string. I propose that this context line only be output when requesting the data as the default "table" format OR to supply another argument to not render the context line.

**Example of problem**

_Command_
```
zapier versions --format=json
```
_Returns_
```
All versions of your app "Example" listed below. <--- This makes the output invalid JSON

[
  {
    "Version": "1.0.41",
    "Platform": "5.0.0",
    "Users": "5",
    "Deployment": "non-production",
    "Deprecation Date": "null",
    "Timestamp": "2018-02-20T14:55:18"
  },
 {
    "Version": "1.0.40",
    "Platform": "5.0.0",
    "Users": "0",
    "Deployment": "non-production",
    "Deprecation Date": "null",
    "Timestamp": "2018-02-20T14:55:18"
  }
]
```

**Solution Example**

_Command_
```
zapier versions --format=json --without-context
```

_Returns_
```
[
  {
    "Version": "1.0.41",
    "Platform": "5.0.0",
    "Users": "5",
    "Deployment": "non-production",
    "Deprecation Date": "null",
    "Timestamp": "2018-02-20T14:55:18"
  },
  {
    "Version": "1.0.40",
    "Platform": "5.0.0",
    "Users": "0",
    "Deployment": "non-production",
    "Deprecation Date": "null",
    "Timestamp": "2018-02-20T14:55:18"
  }
]
```

**Comment by xavdid** [comment]
Great suggestion! We'll slot something like this in.

**Comment by devert** [comment]
Thanks @xavdid. Glad to hear it. I also noticed, as I dug into this, that the response from commands like `versions` return some ANSI color codes. This is also something that would be nice to either get rid of or provide an argument to get a response without.

**Comment by xavdid** [comment]
Sure, like the colored text output? Is that a compatibility thing or personal preference?

**Comment by tcox5698** [comment]
Longer term solution: Another way to think about this is that we need a programmatic interface to the platform. That is, rather than going through the command line interface which is optimized for humans instead of machines, zapier could instead provide a convenience wrapper for interacting with the zapier platform apis. Or just document the platform apis that the CLI is making use of.

My assumption is that the zapier CLI is adding the ANSI color codes to the responses coming back from the zapier platform api...

**Comment by xavdid** [comment]
That's correct, the colors come from within the cli. Are they something that's really bothering folks? We typically see them as helpful, but could reevaluate if that's not the case. 

Tom, as for the wrapper, that's already what the cli does! All the calls the cli makes you could do by hand. Is there a particular use case you're looking to explore?

**Comment by tcox5698** [comment]
HI @xavdid - Dennis has been using the CLI to automate our app management using Jenkins. So to parse the json out of the output coming from the zapier cli, he has to strip out the ansi coloring characters and strip out any additional comments and output that are not JSON.

Thanks for the response. I suppose we could deduce the API calls by inspecting the CLI code and behavior, but are those calls documented in a more readily consumable format somewhere?

**Comment by devert** [comment]
@xavdid As Tom mentions, we could definitely consider moving to interacting directly with the API verses using the CLI. To your note about the ANSI coloring, I do find that useful when I (as a human) am reading the output of these commands in a terminal. However, if I wanted a machine to use that output when I request it with `--format=json` then I might expect the output to be valid JSON that can be parsed without syntax errors. Having ANSI codes in the output is another thing that makes it invalid JSON, in addition to the context line noted in the issue description.

**Comment by xavdid** [comment]
Got it! Those endpoints aren't documented (since they've previously only been used by the CLI). We don't plan on breaking functionality there, but also we can't promise we won't because the CLI will adapt to those hypothetical changes. That said, all calls go through [this](https://github.com/zapier/zapier-platform-cli/blob/master/src/utils/api.js#L44) method, so it would be pretty straightforward to find out how to make the calls you need. Out of curiosity, which ones are you using? Also If it's helpful, v5 allows you to auth with an environment variable rather than having to use `zapier login`.

You're totally correct that the json output should be totally valid; that's a thing we'll fix. Are you seeing ANSI codes in the json itself, or is that just a general compatibility thing?

**Comment by devert** [comment]
@xavdid Thus far, all the info we need for our CI build process seems to be available in what is returned from the `versions` command. In my findings, when specifying a format of `json` or `raw`, the command outputs the ANSI codes in the last line of the output string, right after the array of JSON items containing info about each version. So I have to strip that out before trying to parse it.

**Comment by xavdid** [comment]
Ah I see! We've got an invisible line down there at the bottom, is that what you're talking about? I can clean all that up. Not sure why it's there at all. 

```
% zapier versions --format=json
All versions of your app "TEST" listed below.

[
  {
    "Version": "1.0.0",
    "Platform": "4.3.2",
    "Users": "2",
    "Deployment": "non-production",
    "Deprecation Date": "null",
    "Timestamp": "2016-12-12T11:53:18"
  }
]
[?25h[?25h
```

**Comment by devert** [comment]
Yep. That's the same output I was seeing. Thanks @xavdid. Look forward to seeing these fixes/improvements in place.

**Comment by xavdid** [comment]
@devert breaking ground here, had a quick follow up question. 

In the case of errors, would you want to see those in the json as well? For example, [this](https://github.com/zapier/zapier-platform-cli/blob/master/src/entry.js#L20-L25) and other errors in `entry`. 

My thinking right now is that `--format=json` will only output the json itself if there are errors. I was thinking about the following:

```json
{
  "error": "requires node version >= 6.10 to run"
}
```

but subsequent steps won't have the keys they're expecting anyway. In that sense, it makes sense to fail loudly with any output. Thoughts?

**Comment by xavdid** [comment]
One more thing - this change will affect the read-only portions any commands that are printing data in a table. Near as I can tell, that's the following:

* apps
* collaborate
* describe
* env
* help 
* history
* invite
* ~link~ is interactive, needs to output a prompt as well
* logs
* validate
* versions

Does that cover your use cases?

**Comment by devert** [comment]
@xavdid This all sounds good to me. As much as possible, if the commands can return an error in a consistent way, that is also valid JSON, then we could capture those errors and exit with the error string. 

Your list of commands above will definitely cover our current use cases. We are currently using `versions` and `env` in our CI build and evaluating the output from those commands. 

NOTE: In addition to `--format=json` output being valid JSON, you might also consider doing the same fixes when passed `--format=raw` as this too returns a JSON-like structure and is actually what I plan to use in our CI tasks.

**Comment by xavdid** [comment]
Sweet! that's good to know. `raw` is mostly similar to `json`, we just don't rename/clean keys. I'll make sure the fixes apply to each. 

As for the errors, they're a little more wrapped up so they're probably out of scope for this fix. That said, for `apps` and `env`, you shouldn't be seeing errors outside our API is having issues, so i'm not too worried.

**Comment by xavdid** [comment]
@devert just wanted to follow up. Since this is a breaking change, the release that includes this fix will take a little longer than normal (we try not to release major versions too often). If you'd like to use this now, you can `npm install -g zapier/zapier-platform-cli#valid-json` and begin using the updated formatting. 

​Let me know if you hit anything that's not supposed to happen!

**Comment by devert** [comment]
@xavdid That makes sense. Thanks for letting me know.
