### ISSUE TITLE
How do you create a resource with multiple hooks?

### ISSUE THREAD

**Issue by janaagaard75** [zapier/zapier-platform-cli#263]
I like the idea of combining everything in a resource, but how do I specify multiple hooks (i.e. both create, update and delete) on a resource? As far as I can tell from the [resourceSchema](https://github.com/zapier/zapier-platform-schema/blob/v5.0.0/docs/build/schema.md#resourceschema), it is only possible to specify a single hook.

I know I can solve my issue by creating my hooks separately, but it seems pretty convenient to combine everything in a single object, so I feel like I am missing something obvious.

**Comment by xavdid** [comment]
Hey there @janaagaard75! The short answer is you can only have one hook per resource. Since the hook describes a behavior (deleted, created, updated, etc), it makes sense to have the hook only report one of those activities. 

How does that sound?

**Comment by janaagaard75** [comment]
So if I have a Product resource and that has web hooks for created, updated, and deleted, I should create three separate triggers, and leave out the `hook` property on my Product resource; whereas if I have an Invoice resource that only has a created web hook, I could group the resource and the hook together using the `hook` property?

**Comment by xavdid** [comment]
Yep! You could also include one of the Product hooks on the resource, but the other two will be separate. Depends how you want to organize it.

**Comment by janaagaard75** [comment]
Thanks for explaining this. I think you should consider replacing the `hook` property with `hooks` and let it accept an array of triggers, but creating separate triggers will work fine for now. :)
