### ISSUE TITLE
EPERM error when running zapier push on Windows

### ISSUE THREAD

**Issue by janaagaard75** [zapier/zapier-platform-cli#270]
On macOS and Ubuntu and can push my app without issues, but on Windows I get the following error when running `zapier push`:

> Error! EPERM: operation not permitted, open 'C:\Users\jaa\AppData\Local\Temp\zapier-cd4b7775\.git\objects\e0\ab2311441335d2f5587c0d938f20642ba41723'

- Adding the `--debug` flag does not give move information.
- Using zapier-platform-cli and zapier-platform-core version 5.0.0 and Windows 10.
- Running the command from an administrator shell still gives the same error.
- 4.x worked fine on Windows.
- I have verified that I can create symbolic links, because I saw that this could be the course for EPERM errors on Windows.

Anybody else experiencing this error? Any hints to what I could look into?

**Comment by eliangcs** [comment]
This looks alike to #82, a permission issue? One thing I always recommend to try is to move your app repo to `C:\Users\Public`. If that solves the problem, it likely has something to do with the folder permission.

**Comment by janaagaard75** [comment]
I just tried pushing from a colleague's computer, and there it works fine, so yes, it's almost certainly a permission issue. I forgot to mention that my main user is not local administrators, but I have another user, that has administrator access. The setup has cause issues with other software, and since my colleague has local admin rights, I'll blame it on this, and close this issue.

The colleague is running Node version 6.10.2 installed, whereas I am using 8.10.0, so I could also try installing another version of Node.

**Comment by janaagaard75** [comment]
My repo is in `C:\Projects`, so I think that this gives it the same rights as `C:\Users\Public`.

**Comment by xavdid** [comment]
That's super weird but i'm glad it's working!
