### ISSUE TITLE
Calls to utils.printData hangs for 'row' format with small displays

### ISSUE THREAD

**Issue by codebycaleb** [zapier/zapier-platform-cli#279]
## What would you like to change?
When running a command with an optional `format` flag set to `row` or `table` (e.g. `zapier apps --format=row`), if the terminal window is "skinny" (i.e. less than 15px), the command will hang indefinitely.

I did some debugging (via chrome's node debugger) and found the offending area I think:
![](https://cdn.zapier.com/storage/photos/96e28375042d66b4de229ce0f99e889b.png)

We get stuck in an infinite loop slicing `rest` when `widthForValue` is non-positive. I'm not entirely familiar with what's going on here but I'm happy to try my hand at fixing this issue – I just need to get a little more familiar with what we're doing here.

## Your Environment

* CLI Version (`zapier -v`): ```zapier-platform-cli/5.0.0
node/v9.5.0```
* Operating System and version: `MacOS High Sierra 10.13.3`

**Comment by zapzap** [comment]
This issue has been copied into our private issue tracker. Thanks for the report! We'll update this as we learn more.
