### ISSUE TITLE
zapier link is confusing when failing (EG: trying to link a v2 app)

### ISSUE THREAD

**Issue by cbetta** [zapier/zapier-platform-cli#28]
I've been trying to link an app using `zapier link` and all I'm getting is this:

```
 zapier link                      

Which app number do you want to link? (Ctrl-C to cancel) 58305
Which app number do you want to link? (Ctrl-C to cancel) 58305
Which app number do you want to link? (Ctrl-C to cancel) 58305
Which app number do you want to link? (Ctrl-C to cancel) 
```

It doesn't do anything and just keeps asking for the number.

**Comment by bryanhelmig** [comment]
That is weird! Can you do `zapier link --debug` and hit us with the output?

**Comment by cbetta** [comment]
```
zapier link --debug
>> GET https://zapier.com/api/platform/cli/check
<< 200
<< {"success": true}

>> GET https://zapier.com/api/platform/cli/apps
<< 200
<< {"objects": []}


Which app number do you want to link? (Ctrl-C to cancel) 58305
Which app number do you want to link? (Ctrl-C to cancel) 
```

It seems my apps hash is empty. I have one Beta app on my account though.

**Comment by bryanhelmig** [comment]
Is it a V2 app? IE: did you build it in the browser?

V2 (browser built) apps are not compatible with the CLI.

We should have a better error message regardless.

**Comment by cbetta** [comment]
Yes. It is! That explains the problem. I exported it using the CLI.

**Comment by bryanhelmig** [comment]
Cool, I am going to adjust the issue and we'll address the confusion!
