### ISSUE TITLE
TypeError: value.replace is not a function

### ISSUE THREAD

**Issue by marcboquet** [zapier/zapier-platform-cli#297]
We were getting this error when running `zapier convert`:
```
TypeError: value.replace is not a function
    at Object.keys.forEach.key (lodash.templateSources[74]:19:19)
    at Array.forEach (<anonymous>)
    at eval (lodash.templateSources[74]:17:24)
    at /usr/local/lib/node_modules/zapier-platform-cli/lib/utils/convert.js:93:69
    at <anonymous>
```

Turns out there was an extra `"v": 2` key in our `"auth_mapping"` and the code was trying to run regex on the integer.

We made it work by adding `toString()` in this line:
https://github.com/zapier/zapier-platform-cli/blob/bbf4856ee1bc90a203d5a878dbc151ed06b0409b/scaffold/convert/header.template.js#L8

```javascript
value = value.toString().replace(/\{\{(\w+)\}\}/g, "${bundle.authData['$1']}");
```

Not sure this is the right fix, but maybe it helps other people.

**Comment by zapzap** [comment]
This issue has been copied into our private issue tracker. Thanks for the report! We'll update this as we learn more.

**Comment by eliangcs** [comment]
@marcboquet thanks for reporting! Your solution looks good and I made a PR addressing this: #305.
