### ISSUE TITLE
"Test this Step" spins forever when a search returns an empty array

### ISSUE THREAD

**Issue by mlms13** [zapier/zapier-platform-cli#300]
Using CLI and Core version 5.1.0, I previously had a Search that returned a 404 when no results were found. Per the instructions [here](https://zapier.com/developer/documentation/v2/appdevguide-searches/#response-content), I changed that route in my application to return an empty array in that case. After making this change, I found that "Test this Step" would spin forever on input that produced no results. There are no errors in `zapier logs`.

Here is a very reduced snippet that produces the same results:

```js
  searches: {
    "property": {
      key: "property",
      noun: "Property",
      display: {
        label: "Property Search",
        description: "Search for a property by UUID"
      },
      operation: {
        inputFields: [
          {
            key: "property_uuid",
            required: true
          }
        ],
        perform: (z, bundle) => Promise.resolve([])
      }
    }
  }
```
For the sake of testing, I set the `perform` function to always return a promise of an empty array. The actual zap seems to behave as expected, but the "Test" step just spins forever:

![screen shot 2018-04-16 at 17 49 16](https://user-images.githubusercontent.com/1105543/38840936-2096952a-419f-11e8-847c-6fadfcf9a9fd.png)

**Comment by mlms13** [comment]
While the test is spinning, if I click to another step, then click back to the test, it looks like this:

![screen shot 2018-04-16 at 18 03 19](https://user-images.githubusercontent.com/1105543/38841208-9884c02e-41a0-11e8-97e3-bf10d00a9f94.png)

So that all seems correct. Maybe the issue is just that it's not redrawing the UI after the promise is done?

**Comment by xavdid** [comment]
@mlms13 thanks for the report!

This was an issue with the Zapier editor itself and not anything CLI specific. We've merged the fix on our end and if it's not out in the wild yet, it will be soon. 

Let us know if you see anything else weird!
