### ISSUE TITLE
files.js fixhome function isn't properly refactoring the dir parameter

### ISSUE THREAD

**Issue by FrancisBourgault** [zapier/zapier-platform-cli#31]
Found while using "zapier init appname --template=minimal"

Issue: Instead of replacing the start of the path by Home or UserProfile, FixHome function replace just the '~' and  broke the path.

Here's an exemple: 

Path before replace : "C:\Users\USERUS~1\AppData\Local\Temp\tmp-14492zVmPdO8Gh1LA"
Path after : "C:\Users\USERRGC:\Users\useruserus1\AppData\Local\Temp\tmp-26552m3v9enWUHF3D\zapier-template.zip"

Path after (with indication) : C:\Users\USERRG [[[C:\Users\useruserus]]] 1\AppData\Local\Temp\tmp-26552m3v9enWUHF3D\zapier-template.zip

Sugestion: Make a substring of the start of the path (between start and first index of '~')

**Comment by bryanhelmig** [comment]
Thanks for reporting @FrancisBourgault - watch for fix in https://github.com/zapier/zapier-platform-cli/pull/32.
