### ISSUE TITLE
zapier-platform-schema documentation possibly incorrect

### ISSUE THREAD

**Issue by silverp1** [zapier/zapier-platform-cli#311]
I spent a fair amount of time trying to figure out why I was receiving the following error on `zapier test`:

```
Validating project locally.
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ = 1 =                                                                                                                        │
│     Property │ App.triggers.incident.operation                                                                               │
│     Message  │ is not any of </BasicPollingOperationSchema>,</BasicHookOperationSchema>                                      │
│     Links    │ https://github.com/zapier/zapier-platform-schema/blob/v5.2.0/docs/build/schema.md#basicpollingoperationschema │
│              │ https://github.com/zapier/zapier-platform-schema/blob/v5.2.0/docs/build/schema.md#basichookoperationschema    │
└──────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
Your app is structurally invalid. Address concerns and run this command again.
```

I followed the requirements of the schema here: https://github.com/zapier/zapier-platform-schema/blob/master/docs/build/schema.md#basicpollingoperationschema

It doesn't appear as though `outputFields` are required, but I kept getting this error until I added that field. 

## What would you like to change?
Flip the bit on basicPollingOperationSchema `outputFields` from no to yes. Happy to provide an example if you folks think it was just something dumb I did :+1: 

## Your Environment
* CLI Version (`zapier -v`): `zapier-platform-cli/5.2.0
zapier-platform-core/5.2.0
node/v6.13.0`
* Operating System and version: MacOS 10.13.2

**Comment by silverp1** [comment]
So this is what I wrote yesterday:

```
'use strict';

const sample = require('../samples/triggerIncident');

const triggerIncident = (z, bundle) => {
  const responsePromise = z.request({
    method: 'GET',
    url: `https://google.com`,
  });
  return responsePromise
    .then(response => JSON.parse(response.content));
}

module.exports = {
  key: 'triggerIncident',
  noun: 'Triggerd Incidents',

  display: {
    label: 'New Incident',
    description: 'Triggers when a new incident is added.',
  },

  operation: {
    inputFields: [],
    perform: triggerIncident,
    sample: sample
  }
}
```

Though, in revisiting this, it does seem to validate now. No idea what is going on here, apologies.

**Comment by xavdid** [comment]
No problem at all!

It just struck me as weird because `outputFields` isn't required on either structure, so my guess is that there was something else missing or confounding the example (maybe a missing sample or something). 

If it comes back, definitely let me know!
