### ISSUE TITLE
Node 8 support (Lambda now supports v8.10)

### ISSUE THREAD

**Issue by toddbluhm** [zapier/zapier-platform-cli#315]
Any timeframe for supporting Node 8 now that AWS Lambda supports it? Hopefully should be a seamless upgrade for most.

AWS article: https://aws.amazon.com/blogs/compute/node-js-8-10-runtime-now-available-in-aws-lambda/

**Comment by xavdid** [comment]
@toddbluhm no specific time frame right now, but it's definitely on our radar! If I had to guess, it'll be ready for our next major version on 6 weeks, but that's just a guess.
