### ISSUE TITLE
Why is zapier-platform-core UNLICENSED?

### ISSUE THREAD

**Issue by wking** [zapier/zapier-platform-cli#318]
[Here][1]'s its `package.json` entry.  According to [the npm docs][2], that means:

> ... you do not wish to grant others the right to use a private or unpublished package under any terms

That puts all Zapier apps (who will depend on the core package and download it as a part of `npm install`) in a questionable legal state.  Could you consider adopting a license for the core project?  Even if it's something like:

> Everyone is permitted to copy and distribute verbatim copies of this package, but changing it is not allowed.

EDIT: zapier-platform-cli is [also UNLICENSED][3], and probably needs a license as well to allow folks to install and run it locally.

[1]:  https://github.com/zapier/zapier-platform-core/blob/v6.0.0/package.json#L8
[2]: https://docs.npmjs.com/files/package.json#license
[3]: https://github.com/zapier/zapier-platform-cli/blob/v6.0.0/package.json#L8

**Comment by xavdid** [comment]
My understanding is that this is intentional. This was the answer elsewhere: 

> We're not planning on placing any of the standard open source licenses on our platform cli, core, schema, etc. repositories. 

> Right now the intention is that you are welcome to freely use our unlicensed repositories in the normal lifecycle of developing an integration with Zapier (which includes any CI, deployment processes, test harnesses, etc.) as outlined in our developer terms of service, but not for anything else outside of that.

additionally, the open source libraries are covered under our platform terms: https://zapier.com/platform/tos
