### ISSUE TITLE
zapier-platform-core npm audit issues

### ISSUE THREAD

**Issue by wking** [zapier/zapier-platform-cli#319]
I've just filed #317 with a vulnerability reported by `npm audit` due to a zapier-platform-cli dependency.  There are also a number of issues with `zapier-platform-core`.  I'd file a pull-request against `zapier-platform-core`, but it's [unlicensed][1] (more on that in #318).  From an app perspective, I'm mainly interested in getting lodash bumped to 4.17.5+ to avoid [this][2], but there are a number of other issues that you probably want to fix for your own benefit, including [this issue][3] with [sshpk <1.14.1][4].

[1]: https://github.com/zapier/zapier-platform-core/blob/v6.0.0/package.json#L8
[2]: https://nodesecurity.io/advisories/577
[3]: https://nodesecurity.io/advisories/606
[4]: https://github.com/zapier/zapier-platform-core/blob/v6.0.0/package-lock.json#L4814-L4815

**Comment by xavdid** [comment]
I've opened PRs in all 3 repos to address. I took a look through and nothing jumps out as urgent, but it is good info!

**Comment by wking** [comment]
The core PR is zapier/zapier-platform-core#87.

**Comment by wking** [comment]
The schema PR is zapier/zapier-platform-schema#46.

**Comment by wking** [comment]
All the PRs have been merged; thanks :).

**Comment by xavdid** [comment]
Thank you! Theu won't get released until later, but the audit will be pretty clean once they do
