### ISSUE TITLE
Expose the zappier_acount_id in the bundle during the operation.perform for Actions

### ISSUE THREAD

**Issue by johnpan** [zapier/zapier-platform-cli#322]
It would be very useful to be able to correlate which zap account asked for what action. Since we do not have this, we have to run oauth.test method to get user info via our server.

**Comment by johnpan** [comment]
Changed zapID to _zapier_account_id

**Comment by xavdid** [comment]
Can you talk a bit more about what you want this info for?

**Comment by johnpan** [comment]
@xavdid What we do is send some information about the user from our server to the zapier app using the reply to oauth.test() method. But we need that data to be sent back to us when there is an Action. It seems we will have to invoke oauth.test() again each time there is an Action to get the data that needs to be sent along with the Action post. Obviously we want to avoid this double call. 
So, since we know the zapier_acount_id from the oauth procedure, we could store a correlation in our server. If we had the zapier_acount_id with every Action, we would not have to hit oauth.test() (this is basically the /api/me route) again. How does that seem to you? Is it not safe to use this var to match the user?

**Comment by johnpan** [comment]
Thank you @xavdid, let me check on that, most possibly it is what we need
