### ISSUE TITLE
Support for expiring Webhooks

### ISSUE THREAD

**Issue by cvanderkolk** [zapier/zapier-platform-cli#325]
More APIs are utilizing an "expiring" Webhook philosophy which requires you to specify an expiration date on subscription, at which point the Webhook would cease to work and need to re-subscribed.

### Case Study

For example, Twitch's webhooks require an expiration time that's max `864000` seconds, or 10 days: https://dev.twitch.tv/docs/api/webhooks-reference/

To utilize webhooks like these, the Zapier CLI would have to store the expiration time, and then re-run the hook subscription method at that time.

### Examples

On a quick search, I found two services with Webhooks that expire:
- Microsoft SharePoint: https://docs.microsoft.com/en-us/sharepoint/dev/apis/webhooks/overview-sharepoint-webhooks
- Microsoft OneDrive: https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/using-webhooks#expiration

Along with Twitch, they seem to follow the pattern discussed in the W3C spec for WebSub (under `hub.lease_seconds`): https://w3c.github.io/websub/#x5-3-hub-verifies-intent-of-the-subscriber (edited)

**Comment by seanspeaks** [comment]
@cvanderkolk FYI, Clio's API follows this as well. Currently we're piggybacking on the OAuth refresh to go retrieve all active webhook subscriptions with Zapier URLs, and updating the expiration dates then. Ideally we'd be able to set that separately.

**Comment by xavdid** [comment]
Discussion here: https://zapier.quip.com/HtuEAgS8RpBy

**Comment by cvanderkolk** [comment]
This is now supported! 🎉 

We will attempt to refresh any Webhook subscription that returns an `expiration_date` key before it expires. We'll take our best stab at the time format, though using ISO8601 is a good practice here. If your API doesn't return the expiration time in a specific `expiration_date` key you will have to rename it before returning it in your Webhook subscription function.

Closing this out! 💃
