### ISSUE TITLE
non-descriptive validation error when field label and helpText are equivalent

### ISSUE THREAD

**Issue by codekirei** [zapier/zapier-platform-cli#334]
## What would you like to change?

When a field's `helpText` and `label` are the same, `zapier validate` fails with a non-descriptive error:

`{{insert field}} is not exactly one from </FieldSchema>,</FunctionSchema>`

Ideally, that error message would state that issue is specifically about the `helpText` and `label`.

## Your Environment

Uncertain — this was reported by a user.

**Comment by xavdid** [comment]
I _think_ this comes from the style checks since I know that's something we check for there. No clue why it's coming out as a validation error though, i can't find anything in schema that would cause that. @eliangcs might know more?

**Comment by xavdid** [comment]
we've got better validation now, so this is 👍
