### ISSUE TITLE
only dialog for login

### ISSUE THREAD

**Issue by gyurobenjamin** [zapier/zapier-platform-cli#336]
Really hard to login with CLI from CI or with any script. Would be nice something like this:

```
zapier login -email example@email.com -pass MyPassWRD!
```

**Comment by BrunoBernardino** [comment]
@gyurobenjamin thank you so much for the feature request! I think that's a great idea.

Something you can do for now is create a `~/.zapierrc` file with your login's deploy key (once you login locally you should be able to see such file).

**Comment by gyurobenjamin** [comment]
Yes I'm using that one now, thanks

**Comment by ZaneLyon** [comment]
@gyurobenjamin  The deploy key can also be read from an environment variable (ZAPIER_DEPLOY_KEY), if that works better for your CI setup:

https://zapier.github.io/zapier-platform-cli/#testing-in-your-ci

**Comment by gyurobenjamin** [comment]
I was so close, I used ZAPIER_DEPLOYKEY and I wrote it into the zapierrc... Thank you very much!
