### ISSUE TITLE
Zapier Validate should verify the Node version used matches production

### ISSUE THREAD

**Issue by FokkeZB** [zapier/zapier-platform-cli#34]
I ran `zapier validate` and `push` with success, but then when I used it got:

![](https://cdn.zapier.com/storage/photos/844191852c6abec53df548ce40f056fa.png)

**Comment by bryanhelmig** [comment]
Were you not getting the error locally? Did `zapier test` run and have coverage?

I'm not sure _how much_ static analysis we can really be expected to do here. Maybe block scoping is easier - but lots is hard.

**Comment by FokkeZB** [comment]
@bryanhelmig nope, `zapier validate` nor `zapier test` reported it. I guess because it then runs in my local environment which is Node.js 7.x? By the way, I also tried adding the strict mode declarative but that didn't make it work either. I had to resort to `var`.

**Comment by bryanhelmig** [comment]
Yeah, you need to be running Node 4.3.2 @FokkeZB - that would be a better check to ensure versions. Check out `nvm` if you haven't already!

Can you let us know how it behaves on 4.3.2?

**Comment by FokkeZB** [comment]
On 4.3.2 (I use `nvm` indeed) it fails as expected:

```
$ zapier test
/Users/fokkezb/Documents/Zapier/Code/zapier-platform-app-fork/creates/number.js:24
    for (let i = 0; i < bundle.inputData.forks; i++) {
         ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

So, for those devs that use `nvm` we could add a `.nvmrc` and perhaps even error or warn if they run `zapier` with a different version [like we do for the HS extension](https://github.com/zapier/helpscout-chrome-extension/blob/39ea2d440e0ca2d17193ca56450d3bb5d3bcdc50/scripts/launcher.js#L20-L32).

A step further could be to use something like [node-bundler](https://www.npmjs.com/package/node-bundler) to include Node 4.3.2 in the CLI so that it doesn't matter what the user has installed.

What do you think?

**Comment by xavdid** [comment]
We probably don't even need the `.nvmrc` because a lot of people may develop in a later version and transpile down. Being more clear about what versions are needed where is definitely something we could be more clear on (see #4). 

I like the HS extension approach. I think part of `zapier test` could be to verify the version. It's going to change very infrequently, so I think putting it right into the code is safe. I could throw this in a PR:

```js
const requiredVer = 'v4.3.2'
if (process.version !== requiredVer) {
  throw new Error('You are using node ' + process.version + ' -- please use ' + requiredVer + ' with `nvm use`.')
}
```

**Comment by bryanhelmig** [comment]
That makes sense @xavdid - I've been thinking about some "bundled test suites" that this would be a perfect example of one to include.

`zapier test` is just piggybacking `npm test` so if we can figure out a way to include a custom suite of tests - that would be ideal.

**Comment by FokkeZB** [comment]
@xavdid If we're going to have that error in `zapier test` (which I'm all for) then I'd suggest including a `.nvmrc` anyway, since it's convenient for people to switch to the right version. They don't need to, so they can still be on the edge during development.

**Comment by xavdid** [comment]
This is for the output of `zapier init`, right? It's probably fine to put out a default `.nvmrc` since that's an easy thing to edit/delete if the default doesn't fit for the user. I wrote other things but they don't matter if it's optional. 😁  i'll take care of it!

**Comment by FokkeZB** [comment]
@xavdid yes, correct! Thx!
