### ISSUE TITLE
Tests are failing on Node 10.5

### ISSUE THREAD

**Issue by eliangcs** [zapier/zapier-platform-cli#342]
The tests are failing on Node 10.5 because `mock-fs` doesn't work on Node 10.5:

https://github.com/tschaub/mock-fs/issues/238

This doesn't affect production usage but is a bit annoying to see a failing Travis badge.

## What would you like to change?

We have three options:

* Replace Node 10 with Node 10.4 in `.travis.yml`
* Wait for `mock-fs` to fix the issue
* Remove `mock-fs` from our test code

**Comment by xavdid** [comment]
Seems like no action needed on our part for now
