### ISSUE TITLE
incorrect documentation for session auth

### ISSUE THREAD

**Issue by idubinets** [zapier/zapier-platform-cli#345]
https://github.com/zapier/zapier-platform-cli?utm_source=zapier.com&utm_medium=referral&utm_campaign=zapier#session

Take a look the description on the link above. there is a section.

![image](https://user-images.githubusercontent.com/2304959/42457478-42fded50-83a0-11e8-9648-b42f7d7c3b38.png)

**Comment by eliangcs** [comment]
@idubinets thanks for reporting! Created PR #346 to fix this.

**Comment by b-times-b** [comment]
So... the dosumentation over there is outdated?
https://zapier.github.io/zapier-platform-cli/

> Note - For Session auth, authentication.sessionConfig.perform will have the provided fields in bundle.inputData instead of bundle.authData because bundle.authData will only have "previously existing" values, which will be empty the first time the Zap runs.
