### ISSUE TITLE
`zapier upload` should give a meaningful error message when dev hasn't built

### ISSUE THREAD

**Issue by eliangcs** [zapier/zapier-platform-cli#351]
Before a developer builds their project with `zapier build`, running `zapier upload` will just fail silently without any meaningful error messages.

![](https://cdn.zapier.com/storage/photos/5627b065d50eeeb49d6f1c95ba8c7076.png)

## What would you like to change?

If `./build/build.zip` doesn't exist, `zapier upload` should give a hint that they should run `zapier build` first or use `zapier push` command instead.

## Your Environment

* CLI Version (`zapier -v`): 7.1.0
* Operating System and version: Irrelevant

**Comment by shaunc869** [comment]
Here here to that, ran into the same issue!

**Comment by xavdid** [comment]
fixed in #408
