### ISSUE TITLE
Disabling dependency detection wil trigger errors on source (instead of built) files

### ISSUE THREAD

**Issue by Raqbit** [zapier/zapier-platform-cli#366]
I'm using a library called [strong-soap](https://npmjs.org/package/strong-soap) for interfacing with a SOAP API. This package does some dynamic resolution of which files to import, so the dependency injection used with `zapier push` fails and does not include many important parts of the library.

As far as I understand, the `--disable-dependency-detection` flag is made to resolve these kinds of issues, but this means the Zapier CLI also tries to load my source files, which use es6 import/export as my project is based on [zapier-platform-example-app-babel](https://github.com/zapier/zapier-platform-example-app-babel).

This causes the CLI to error out (I'm guessing it's using eslint under the hood, looking at these errors).

`npm run zapier-build && zapier push --disable-dependency-detection --debug`
```
✔ Validating project
⠸ Zipping project and dependencies
 
<path>/src/authentication.js
  1:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

<path>/src/index.js
  1:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

<path>/src/middleware.js
  1:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

<path>/src/resources/index.js
  1:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

<path>/src/resources/<file>.js
  1:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

<path>/src/util.js
  1:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

✖ 6 problems (6 errors, 0 warnings)
```

## What would you like to change?

It would be handy if you could exclude a file/directory from being validated and zipped up. In this case I would exclude my source directory so the CLI would only look at my built `lib` directory, which should work for node 6+.

## Your Environment

* CLI Version (`zapier -v`): `7.2.2`
* Operating System and version: `Ubuntu 18.04`

**Comment by xavdid** [comment]
Great question! We've got just the thing for that. Check out these docs: https://github.com/zapier/zapier-platform-cli#using-npm-modules. Namely, `includeInBuild` in your `.zapierapprc`. You want to leave off `--disable-dependency-detection` (because you only want a few files), but can manually include `lib` in that json.

Let me know if that doesn't work and we can take a look!

**Comment by Raqbit** [comment]
While this seems exactly like the thing I need, specifying this also (just like with `--disable-dependency-detection`) triggers the errors.

Weirdly, when using the `includeInBuild` option it only errors for all `index.js` files, where using `--disable-dependency-detection` triggered the error for every JavaScript file using import/export statements.

To be clear, these errors are not reported when I run `push` without disabling dependency detection and not specifying the `includeInBuild` property in `.zapierapprc`.

---

`.zapierapprc` snippet:
```json
{
  "includeInBuild": [
    "index.js",
    "lib/",
    "node_modules/"
  ]
}
```

**Comment by xavdid** [comment]
Is there a different error for the `index.js` files? 

But yeah, doing all of `node_modules` probably isn't what you want.

Can you expand on errors not showing up during build? Seems like that's where you'd want to see them.

**Comment by Raqbit** [comment]
The errors *are* showing up during build.

---

Errors with `--disable-dependency-detection`:
```
✔ Validating project
⠸ Zipping project and dependencies
 
<path>/src/authentication.js
  1:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

<path>/src/index.js
  1:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

<path>/src/middleware.js
  1:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

<path>/src/resources/index.js
  1:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

<path>/src/resources/<file>.js
  1:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

<path>/src/util.js
  1:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

✖ 6 problems (6 errors, 0 warnings)
```

Errors when using `includeInBuild` in `.zapierapprc`:
```
✔ Validating project
⠸ Zipping project and dependencies
 
<path>/src/creates/index.js
  1:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

<path>/src/index.js
  1:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

<path>/src/resources/index.js
  1:1  error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

✖ 3 problems (3 errors, 0 warnings)
```

**Comment by xavdid** [comment]
Why are `src` files included with `includeInBuild`? does your `index.js` include them?

**Comment by Raqbit** [comment]
No, it does not. It's the same one as the Babel example, just with `.default` added to the import of `lib/`, since a newer Babel version transpiles `export default app` to `module.exports.default` ([See issue](https://github.com/babel/babel/issues/2212)).

**Comment by xavdid** [comment]
That's very odd. 

The way we build the file list is by starting at `index.js` and walking anything it `require`s until we have a big list of files ([code here](https://github.com/zapier/zapier-platform-cli/blob/c9a50848245ed69bf3c6a7f49b1403e1ce5453d3/src/utils/build.js#L47-L95)).

It's hard to debug without seeing all the code, but if I had it, I'd be doing `zapier build --debug` and seeing why the build command gets into the `src` directory at all

**Comment by Raqbit** [comment]
Here's the "zip files" part of the `zapier build --debug` output: https://pastebin.com/Ugf5LUN4.

In this one I removed `node_modules/` from the `includeInBuild`, making it become (exc. `id` and `key`):
```json
{
  "includeInBuild": [
    "index.js",
    "lib/"
  ]
}

```

**Comment by xavdid** [comment]
Yeah, see, right at the bottom: 

```
  package.json
  src/creates/index.js
  src/index.js
  src/resources/index.js
```

so I bet something in `package.json` references `src` somehow, which is grabbing your creates and resources.

**Comment by Raqbit** [comment]
`package.json` without `name`,`version` and `description`:
```json
{
 "main": "index.js",
  "scripts": {
    "zapier-build": "rm -rf lib && babel src --out-dir lib",
    "zapier-dev": "rm -rf lib && babel src --out-dir lib --watch",
    "zapier-push": "npm run zapier-build && zapier push",
    "zapier-validate": "npm run zapier-build && zapier validate",
    "prepare": "npm run zapier-build",
    "pretest": "npm run zapier-build",
    "test": "mocha --recursive lib/test --require babel-polyfill"
  },
  "engines": {
    "npm": ">=5.6.0"
  },
  "dependencies": {
    "babel-polyfill": "^6.26.0",
    "babel-preset-minify": "^0.5.0",
    "moment": "^2.22.2",
    "strong-soap": "^1.13.2",
    "zapier-platform-core": "7.2.2"
  },
  "devDependencies": {
    "@babel/cli": "^7.1.2",
    "@babel/core": "^7.1.2",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0",
    "@babel/plugin-transform-regenerator": "^7.0.0",
    "@babel/preset-env": "^7.1.0",
    "eslint": "^5.6.0"
  }
}
```

**Comment by Raqbit** [comment]
Full output of `zapier build --debug`: https://hastebin.com/runojemiba.txt.

For read-only source  access I'd have to get permission from someone.

**Comment by codebycaleb** [comment]
Hey, @Raqbit – I just talked things over with @xavdid and we think we've got the cause / solution here. 

![](https://zappy.zapier.com/B1AA773D-25C7-4D01-9B0B-474A6E1CAB1C.png)

When you specify `index.js` in your `includeInBuild`, we're using a RegExp that's matching all instances of `index.js`. Could you swap `index.js` out and put `lib` in, instead? I think we already grab the root `index.js` by default. If that doesn't work, try anchoring the `index.js` line via `"^index.js"`. 😄

**Comment by Raqbit** [comment]
Yup! That was it.
Seems like I defaulted to thinking they would be glob-patterns.

Thanks for all the help @codebycaleb & @xavdid.
