### ISSUE TITLE
Deasync.node is not included in the zip file when we build from windows os

### ISSUE THREAD

**Issue by KostasSavvopoulos** [zapier/zapier-platform-cli#369]
## What would you like to change?
zapier build and zapier push do not include the deasync.node which is needed from the zapier-platform-legacy-scripting-runner in the build.zip file when we run the build command from windows.
The reason is that the path separator is not '/' in windows so the condition in build.js
```
filePath.endsWith(`/bin/linux-x64-node-${nodeMajorVersion}/deasync.node`)
```
never returns true.

Maybe you could check the separator as you already do in 
```
filePath.match(path.sep === '\\' ? /aws-sdk\\apis\\.*\.json/ : /aws-sdk\/apis\/.*\.json/)
```
 
* CLI Version (`zapier -v`): 7.3.0
* Operating System and version: windows 10

**Comment by eliangcs** [comment]
The fix will be shipped in the next release, 7.4.0.
