### ISSUE TITLE
Way to reference parent field of trigger in 'dynamic' context

### ISSUE THREAD

**Issue by joshuathompson** [zapier/zapier-platform-cli#371]
## What would you like to change?
Our product allows customers to create database tables/columns and thus everything is dynamic. As such, once a customer selects a table we grab the columns for them with a function that generates fields such as:

`{  
    key: 'field_xx',
    label: 'blah blah',
    dynamic: 'connection.id.label'
}`

In this case the field has a `dynamic` property because it's actually a foreign key field that points to another table. In these cases we need to use pagination because the foreign table could have 100,000 rows and cause Zapier to hit the 30s timeout limit. Problem is, we need to use the `field_xx` key defined above IN the connection trigger's `perform` command in order to make the proper API request and I can find no way to possibly reference that information.

Is it possible for there to be something like `meta.bundle.parentKey` or something in the context of a child dynamic trigger? Alternatively giving a function or some other input to `dynamic` to support more... dynamic cases. 😄 

Some conversation from Slack: https://zapier-platform.slack.com/archives/C2S5DGF6G/p1540390608000100

**Comment by xavdid** [comment]
That does seem really useful! It's a change that would happen on the server side, but we can keep this issue here as reference and to collect info. We're pretty busy right now, but i'll move this into our tracker and we'll see how it goes. 

Thanks for reporting!

**Comment by zapzap** [comment]
This issue has been copied into our private issue (as [PDE-518](https://zapierorg.atlassian.net/rest/api/2/issue/17289)) tracker. Thanks for the report! We'll update this as we learn more.

**Comment by xt1** [comment]
This is a similar issue: #399

**Comment by xt1** [comment]
How to handle dynamic triggers for user-defined fields.

Relevant chunk of the Slack conversation from Caleb McQuillin:
https://zapier-platform.slack.com/archives/C2S5DGF6G/p1540390608000100

Imagine a Trigger that is intended to power a dynamic dropdown like so:

```js
const generic_dynamic_dropdown = {
  key: 'dynamic_dropdown',
  noun: 'Dynamic Entity',
  display: {
    label: 'Get a list of entities based on a type',
    description: 'Trigger for entity lookup dropdowns.',
    hidden: true,
  },
  operation: {
    inputFields: [],
    perform: listDynamicEntity,
    sample: {
      id: 1,
    }
  },
}

const listDynamicEntity = async (z, bundle) => {
  let response = await z.request({
    url: '{{bundle.authData.baseUrl}}/api/entities/';,
    params: {
      sortField: 'createdAt',
      sortOrder: 'desc',
      type: bundle.inputData.entityType,
    },
  });
  response.throwForStatus();
  return response.json;t 
}
```

The Trigger is intended to power the following Action:

```js
const createEntity = {
  operation: {
    inputFields: [
      (z, bundle) => {
        return retrieveDynamicFields();
        // returns [{"key": "contact", "dynamic": "list_dynamic_contact.id.name"}, ...]
      }
    ] 
  }
}
```

All is fine and dandy with this, but as you've said, the problem here is that the dynamic dropdown doesn't know what type of field needs to be retrieved (in this case, it's referencing `bundle.inputData.entityType`, which isn't set. We could have users populate what type of field is being specified, but that could double the number of fields required to set up a Zap.

Instead... we introduce this in our `beforeApp`:

```js
const dynamicDropdownInterceptor = (input) => {
  const re = /^triggers.list_dynamic_(.+?).operation.perform$/
  let entityType
  
  // we're in a method call to a method that doesn't exist, so lets grab the entity type
  // given we know the pattern this will turn the call's method name
  // triggers.list_dynamic_<entitytype>.operation.perform
  // into just <entitytype> which we'll use in the input data
  if (input._zapier.event.method && entityType = input._zapier.event.method.match(re)) { // this _should_ assign entityType if JS works like I think it does
    input.bundle.inputData.entityType = entityType[1]; // injects entityType match into the bundle
    input._zapier.event.method = 'triggers.dynamic_dropdown.operation.perform'; // replaces the intended target method
  }
  return input;
}
```

```js
const App = {
  beforeApp: [
    dynamicDropdownInterceptor,
  ],
  ...
}
```

You may need to do some fiddling to get this to work just right for you, but I hope the concept comes across here.

**Comment by joshuathompson** [comment]
The `beforeApp` functionality solves my issue. Notes for anyone who gets slightly confused by the above post from Slack:

1. When setting the `dynamic` property on a field you embed the information you want to pass along somewhere in the value. e.g. `dynamic: connection_mystring.id.label`
2. You use the `beforeApp` interceptor to get that value and put it onto `bundle.inputData` so you can use that information in a `perform` trigger function or equivalent.
3. You set `input._zapier.event.method` back to the original trigger method so that it actually points to a real trigger/function.

I'm personally fine to close this out but I'm not sure if Zapier is working on an easier method internally.

**Comment by bcooksey** [comment]
For now the `beforeApp` is the solution we have available.
