### ISSUE TITLE
Including a sample in a hidden trigger's polling operation invalidates it

### ISSUE THREAD

**Issue by obahareth** [zapier/zapier-platform-cli#377]
If you include a sample in a trigger where `display.hidden == true`, you get this error when running `zapier validate`:

```
Validating project locally.
== Property
App.triggers.resource.operation
== Message
is not any of </BasicPollingOperationSchema>,</BasicHookOperationSchema>
== Links
https://github.com/zapier/zapier-platform-schema/blob/v7.4.0/docs/build/schema.md#basicpollingoperationschema
https://github.com/zapier/zapier-platform-schema/blob/v7.4.0/docs/build/schema.md#basichookoperationschema

Your app is structurally invalid. Address concerns and run this command again.
```

This is what my trigger looks like:

```js
const sample = require('../samples/sample-resource-list')

const triggerResource = (z, bundle) => {
  const responsePromise = z.request({
    url: `api.example.com/resources`,
  })
  return responsePromise.then(response => JSON.parse(response.content))
}

module.exports = {
  key: 'resource',
  noun: 'Resource',

  display: {
    label: 'Get Resources',
    hidden: true,
    description:
      "The only purpose of this trigger is to populate the dropdown list of resources in the UI, thus, it's hidden.",
  },

  operation: {
    perform: triggerResource,
    sample: sample,
  },
}
```

If you remove the sample, e.g. making operation look like this:

```js
  operation: {
    perform: triggerResource
  }
```

then running `zapier validate` will not produce any errors.

## What would you like to change?

Allow adding samples for hidden triggers, or [update the docs](https://github.com/zapier/zapier-platform-schema/blob/v7.4.0/docs/build/schema.md#basicpollingoperationschema) to mention that you can't add samples to hidden triggers.

## Your Environment

* CLI Version (`zapier -v`): 7.4.0
* Operating System and version: macOS Mojave 10.14.1 Beta (18B73a)

**Comment by xavdid** [comment]
That's not great! I bet there's something weird going on with our functional validators. Thanks for flagging.

**Comment by zapzap** [comment]
This issue has been copied into our private issue (as [PDE-537](https://zapierorg.atlassian.net/browse/PDE-537)) tracker. Thanks for the report! We'll update this as we learn more.

**Comment by stevelikesmusic** [comment]
@obahareth are you still having this problem? I was not able to reproduce with your example trigger. What does the sample look like?

**Comment by obahareth** [comment]
hey @stevelikesmusic, I sadly no longer have access to that codebase so I can't find out if it's still happening or not, but the sample file looked like this:


```js
module.exports = [
  {
    id: '5af2ece68061ec0004ebe744',
    name: 'Political Affairs',
  },
  {
    id: '5af2ece68061ec0004ebe745',
    name: 'Social Affairs',
  },
]
```

**Comment by xavdid** [comment]
My guess is that it was complaining about the sample being an array instead of an object. I'm not sure why the `hidden` flag mattered. 

In any case, we've got better error messages out now, so if we do run into it again, we'll be able to better diagnose the issue. thanks a bunch!
