### ISSUE TITLE
Field validation

### ISSUE THREAD

**Issue by eliangcs** [zapier/zapier-platform-cli#383]
## What would you like to change?

This feature request came from a user in Zapier Platform Slack.

It'd be better if devs can provide a `validate` function (such as `triggers.KEY.operation.validate`) to validate the values of input fields. In this `validate` function, devs can do advanced validation like "if the account number is in my system" or "if a credit card number is valid," etc.  And in Zap editor, users don't have to wait until the test step to see a validation error.

**Comment by xavdid** [comment]
this is cool and more of an editor product decision. Given that, i've added to our product feedback database and will close this.
