### ISSUE TITLE
Provide zap.name and event in the performSubscribe function

### ISSUE THREAD

**Issue by matthewheath** [zapier/zapier-platform-cli#385]
The Web Builder exposes the name of the Zap (`zap.name`) as well as the `event` field which allows you to determine which trigger this function is being called for, however the CLI builder doesn't provide access to those values.

I think it would make sense to expose these in the CLI builder too for developers to use. At present, we only expose the `zap.id` per #137.

**Comment by xavdid** [comment]
This isn't on our roadmap as we're pretty selective about when/how we'll give info about user zaps.
