### ISSUE TITLE
Dynamic fields with dynamic lists not supported

### ISSUE THREAD

**Issue by xt1** [zapier/zapier-platform-cli#399]
We have CRM system that allows users to define custom fields, some of which may be dropdown lists. The lists can also be defined by users. So one site may have udef_a and udef_b, which reference list C and D, which contains elements E, F and G,H.  Another site may have udef_x with a list Y with element Z1 and Z2 in it.

## What would you like to change?

Currently the way to handle this is to declare the field dynamic, with a reference to a trigger:

        {key: 'udefa', type: 'integer', label: 'Udef A',  dynamic: 'udefListC.id.name'},
        {key: 'udefb', type: 'string', label: 'Udef B',  dynamic: 'udefListD.id.name'}

However, triggers need to be declare in the App manifest, so there is no way to declare the user-specific lists there. 

```
  triggers: {
    [listCategory.key]: listCategory,
    [listUdef.key]: listUdef
  }
```

A catch-all trigger like `listUdef` can be declared, but there is no way to communicate any parameters from the user-defined field definition to the trigger.

The trigger is called with an empty inputfield.

I would like the dynamic declaration passed in, so that the trigger can respond with the appropriate list items. Currently the dynamic property is only used internally in the framework. I would like to use it to determine which list to retrieve, so that my dynamic fields can have the right dynamic list items in them.

I would like to be able to define fields like this:

        {key: 'udefa', type: 'integer', label: 'Udef A',  dynamic: 'udefList.id_C.name'},
        {key: 'udefb', type: 'string', label: 'Udef B',  dynamic: 'udefList.id_D.name'}

and then in my `udefList` trigger check the inputFields.dynamic for the string value, so that I can return list items E and F when it sees id_C, and items G and H when it sees id_D.

Alternatively, add an extra parameter to the fields definitions:

        {key: 'udefa', type: 'integer', label: 'Udef A',  dynamic: 'udefList.id.name', dynamicArg: 'C'},
        {key: 'udefb', type: 'string', label: 'Udef B',  dynamic: 'udefList.id.name', dynamicArg: 'D'}

so I don't have to muck around with string decoding.

## Your Environment
* CLI Version (`zapier -v`): 7.6.1
* App id: App3680

**Comment by xt1** [comment]
Workaround found on Slack

How to handle dynamic triggers for user-defined fields.

Relevant chunk of the Slack conversation from Caleb McQuillin:
https://zapier-platform.slack.com/archives/C2S5DGF6G/p1540390608000100

Imagine a Trigger that is intended to power a dynamic dropdown like so:

```js
const generic_dynamic_dropdown = {
  key: 'dynamic_dropdown',
  noun: 'Dynamic Entity',
  display: {
    label: 'Get a list of entities based on a type',
    description: 'Trigger for entity lookup dropdowns.',
    hidden: true,
  },
  operation: {
    inputFields: [],
    perform: listDynamicEntity,
    sample: {
      id: 1,
    }
  },
}

const listDynamicEntity = async (z, bundle) => {
  let response = await z.request({
    url: '{{bundle.authData.baseUrl}}/api/entities/';,
    params: {
      sortField: 'createdAt',
      sortOrder: 'desc',
      type: bundle.inputData.entityType,
    },
  });
  response.throwForStatus();
  return response.json;t 
}
```

The Trigger is intended to power the following Action:

```js
const createEntity = {
  operation: {
    inputFields: [
      (z, bundle) => {
        return retrieveDynamicFields();
        // returns [{"key": "contact", "dynamic": "list_dynamic_contact.id.name"}, ...]
      }
    ] 
  }
}
```

All is fine and dandy with this, but as you've said, the problem here is that the dynamic dropdown doesn't know what type of field needs to be retrieved (in this case, it's referencing `bundle.inputData.entityType`, which isn't set. We could have users populate what type of field is being specified, but that could double the number of fields required to set up a Zap.

Instead... we introduce this in our `beforeApp`:

```js
const dynamicDropdownInterceptor = (input) => {
  const re = /^triggers.list_dynamic_(.+?).operation.perform$/
  let entityType
  
  // we're in a method call to a method that doesn't exist, so lets grab the entity type
  // given we know the pattern this will turn the call's method name
  // triggers.list_dynamic_<entitytype>.operation.perform
  // into just <entitytype> which we'll use in the input data
  if (input._zapier.event.method && entityType = input._zapier.event.method.match(re)) { // this _should_ assign entityType if JS works like I think it does
    input.bundle.inputData.entityType = entityType[1]; // injects entityType match into the bundle
    input._zapier.event.method = 'triggers.dynamic_dropdown.operation.perform'; // replaces the intended target method
  }
  return input;
}
```

```js
const App = {
  beforeApp: [
    dynamicDropdownInterceptor,
  ],
  ...
}
```

**Comment by xavdid** [comment]
As your workaround is the best way to do this (that's why we made `beforeApp`), I'm going to go ahead and close (since the other changes you asked for are probably out of scope).
