### ISSUE TITLE
Dehydration not supported on inputfield choice array

### ISSUE THREAD

**Issue by xt1** [zapier/zapier-platform-cli#400]
Similar to issue #399
Want to make dynamic list of fields without fetching all dropdown list items up front.

I have a function that returns custom fields. 
Some of these fields have dropdown lists.
I would like to populate the dropdown list choices on demand.

## What would you like to change?

Input fields are defined through a function:

      inputFields: [
        {key: 'name', required: true, type: 'string', label: 'Company name.'},
        {key: 'category', required: false, type: 'string', label: 'Category',  dynamic: 'mdoCategory.id.name'},
        getUdefInputs
       ],

The `getUdefInputs` function adds user-defined fields, with a dehydrated function populate the list items:

```js
  const getUdefInputs = (z,bundle) => {
    let udef1 = z.dehydrate( listUdef.operation.perform, { listname: 'udef_1'});
    let udef2 = z.dehydrate( listUdef.operation.perform, { listname: 'udef_2'});
    return [
      {key: 'udef1', type: 'integer', label: 'Udef 1',  choices: udef1 },
      {key: 'udef2', type: 'string', label: 'Udef Two',  choices: udef2 }   ]
  };
```

The dehydrated functions are not re-hydrated when the dropdown list is shown. (See screenshot)
![image](https://user-images.githubusercontent.com/3820037/52629422-eb1ec300-2eb9-11e9-986a-8cf5b252df94.png)

I would like the choices list to be re-hydrated on demand, so that I can populate the choices once, when someone clicks on it, rather than having to pre-fetch all the choices during inputfield construction.

## Your Environment
* CLI Version (`zapier -v`): 7.6.1
* App id: App3685

**Comment by xavdid** [comment]
This is working as intended. Dehydration is meant to do defer expensive calls between multiple zap steps.

In this case, it sounds like a second function that usually no-ops is the way to go. when it does fire (based on whatever pre-reqs you need) it can do the request for the defined user fields and return them as choices. Does that make sense?
