### ISSUE TITLE
`zapier login` fails to authenticate Google login credentials

### ISSUE THREAD

**Issue by akflaherty** [zapier/zapier-platform-cli#402]
If a user account was created by signing in to Google, then entering that email address and password will not work with `zapier login`.
The following error is returned:
```bash
Error! "https://zapier.com/api/platform/cli/keys" returned "401" saying "Could not authenticate you."
```

## What would you like to change?
Add a command line argument to zapier login, to generate the zapierrc file for Google accounts

## Your Environment

* CLI Version (`zapier -v`): 7.6.1
* Operating System: Windows 10
* Node.js Version: 8.11.4 

 

I was able to successfully log in with an account generated directly through Zapier with a username and password.

**Comment by eliangcs** [comment]
@akflaherty when you signed up Zapier with your Google account, we generated a random password for your Zapier account. You and we can never retrieve that random password, so you need to reset it from https://zapier.com/app/login/forgot and use that password in `zapier login`. Let us know if it still doesn't work.

**Comment by xavdid** [comment]
That is to say, this is working as intended (albeit unclear). Accounts created purely through google have no password. To use the CLI, you need to create a password via a password reset (as mentioned above) and then you'll be able to log in. 

We should definitely document this more clearly though!

**Comment by jbaranski** [comment]
I ran into the same problem. It's not clear until reading this.

**Comment by xavdid** [comment]
Sorry about that! We've got work scheduled to resolve this in the next version. Thanks for your patience!

**Comment by xavdid** [comment]
8.1.0 gives a warning about this and #420 (unreleased, but coming soon-ish) has similar messaging (and an eventual workaround). Going to go ahead and close.

Thanks for the report!
