### ISSUE TITLE
zapier logs should have an option for continuous monitoring

### ISSUE THREAD

**Issue by hasahmed** [zapier/zapier-platform-cli#409]
`zapier logs` should have an option for continuous monitoring. Heroku has an option like this (`--tail` i think) that keeps the connection to the logs, allowing you to see logs in real time. This would be a nice feature for `zapier` cli tool.

**Comment by xavdid** [comment]
That would be cool! We don't have anything like that currently planned, but will keep it in mind.

**Comment by xavdid** [comment]
we talked this over and while it is a cool feature, we have no plans to implement it at this time. Thanks a bunch for suggesting it though and we'll revisit this issue if we ever circle back!
