### ISSUE TITLE
Question: bundle.meta.page always 0 when click "Get More Samples" button

### ISSUE THREAD

**Issue by folencao** [zapier/zapier-platform-cli#426]
Hi, 

When I click "Get More Samples" button to load more samples, no matter how many clicks I did, bundle.meta.page always zero, so turn out it cannot load more samples, please advise.

Thanks,

**Comment by xavdid** [comment]
Hi there! Sorry you're having this problem. If you could write into contact@zapier.com with a link to a zap that's showing the issue, that would be a huge help. that sounds like an issue with the product and not this code specifically. thanks!
