### ISSUE TITLE
Set timezone when displaying logs

### ISSUE THREAD

**Issue by semenmiroshnichenko** [zapier/zapier-platform-cli#431]
`zapier logs` produces data with a timestamp column, but currently in Central Time. I would wish to being able to define/change a time zone displayed in logs, ideally saving this as account settings.

CLI Version 8.1.0

**Comment by xavdid** [comment]
Great suggestion! I've just merged a fix for this. `zapier logs` will now respect your time zone settings as outlined in your [profile](https://zapier.com/help/settings/#profile). It'll be live within the next 24 hours. 

Thanks a bunch!
