### ISSUE TITLE
Unable to install 8.1.0 on Windows Node 12.2.0

### ISSUE THREAD

**Issue by danspam** [zapier/zapier-platform-cli#434]
When attempting to install v8.1.0 using npm 6.9.0 and node 12.2.0 an error occurs when it attempts to build contextify. This does not occur with v8.0.1, so contextify must be a new dependency?

**Comment by xavdid** [comment]
Thanks for the report! I'm seeing a similar thing. 

FWIW, at least on my end, it looks like the install succeeds despite the failed install because contextify is optional: 

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: contextify@0.1.15 (node_modules/zapier-platform-cli/node_modules/contextify):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: contextify@0.1.15 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ zapier-platform-cli@8.1.0
added 60 packages from 100 contributors, removed 3 packages and updated 12 packages in 5.75s
```

Are you seeing the same thing or is there a failure message you can provide?

**Comment by danspam** [comment]
Ah, yes I see the same. It was a sea of red, so I just assumed it was a complete failure. Should have paid more attention to the last three lines.

**Comment by xavdid** [comment]
Yeah, I totally get it. I wish npm was more clear about that. 

In any case, i've found why we're including `contextify` and we don't really need it, so i'll pull it from deps in the next version. thanks a bunch!
