### ISSUE TITLE
All data in request body is getting converted to strings

### ISSUE THREAD

**Issue by bcooksey** [zapier/zapier-platform-cli#436]
## What would you like to change?

While testing something in legacy-scripting-runner, I found that all the numbers in my request are being converted to strings. Tracing it through with debugger, I landed on the coersion happening in [this block](https://github.com/zapier/zapier-platform-core/blob/48ddbd4a355723bd04143ef64da9319c1d4e1ebf/src/tools/cleaner.js#L47-L49). This change was introduced in https://github.com/zapier/zapier-platform-core/pull/152

I believe this may only be an issue for legacy-scripting-runner, because it does a [round of replacement](https://github.com/zapier/zapier-platform-legacy-scripting-runner/blob/75298f95b10ad6d897906a687e92883b84391773/index.js#L518) itself before calling z.request.

## Your Environment

This is a build of core from master with legacy-scripting-runner dependency bumped to 3.1.0

**Comment by bcooksey** [comment]
I think the root issue that converted apps are running into is this [early return](https://github.com/zapier/zapier-platform-core/blob/48ddbd4a355723bd04143ef64da9319c1d4e1ebf/src/tools/cleaner.js#L60). Since there is no curlies, we return out as is, which means we skip the part where we were supposed to [set out back to the actual value](https://github.com/zapier/zapier-platform-core/blob/48ddbd4a355723bd04143ef64da9319c1d4e1ebf/src/tools/cleaner.js#L79-L81).

As far a solutions go for this one, we could go a couple routes:

1) Remove the number -> string coercion and put that down in the logger, which is what https://github.com/zapier/zapier-platform-core/pull/152 was originally a fix for
2) See if legacy-scripting-runner still needs to do this early curly replacement. Maybe that can be left to core now that we've improved it.

**Comment by xavdid** [comment]
this is fixed in https://github.com/zapier/zapier-platform-core/pull/155 if you want to take a peek.
