### ISSUE TITLE
Error when `build` folder not found

### ISSUE THREAD

**Issue by loganvolkers** [zapier/zapier-platform-cli#44]
I was following along to the [Zapier CLI Tutorial](https://github.com/zapier/zapier-platform-cli/wiki/Tutorial) and ran into an error with `zapier push`. 

![image](https://cloud.githubusercontent.com/assets/1157086/24183820/c40dc88c-0e87-11e7-8abc-752ea105fd77.png)

Peeling back the onion, found that is just an alias for `zapier build` and `zapier upload`. Turns out there was an error if the `build` folder doesn't exist.

![image](https://cloud.githubusercontent.com/assets/1157086/24183745/7405a01c-0e87-11e7-9169-2e8ed415b2c6.png)

It would be good if either: 
 
 a) the default project template just included an empty `build` folder
 b) `zapier build` would create the build folder if it doesn't exist

**Comment by BrunoBernardino** [comment]
Oh boy! Thank you for reporting this @loganvolkers will work on it!

**Comment by BrunoBernardino** [comment]
Will be fixed in 1.0.3!
