### ISSUE TITLE
OAuth2 redirect not calling getAccessToken

### ISSUE THREAD

**Issue by deevus** [zapier/zapier-platform-cli#59]
I'm trying to implement OAuth2 and it's failing after the redirect stage. 

![image](https://cloud.githubusercontent.com/assets/856194/24535016/39814ec6-161d-11e7-9e11-fe918bb8fc79.png)

I have put a `z.console.log` in the `getAccessToken` function and it is never being called. Any ideas what the problem could be?

To clarify, it is hitting the authorize endpoint fine, and redirecting to `redirect_uri` with a code generated by our server.

**Comment by BrunoBernardino** [comment]
Hi @deevus,

Thank you for using our CLI Platform, I'm sorry to hear you're having issues!

Is there some code we can take a look at? Have you compared your code to https://github.com/zapier/zapier-platform-example-app-oauth2/blob/master/authentication.js for example ?

If you want to deal with this more privately, feel free to email us at partners@zapier.com.

**Comment by deevus** [comment]
@BrunoBernardino I'm actually speaking to a Support Engineer (Jacob) over e-mail. I sent the source code to him.
