### ISSUE TITLE
Zapier Validate searchOrCreate from resource problem

### ISSUE THREAD

**Issue by amodliszewski** [zapier/zapier-platform-cli#66]
When validating app with a resource that have list, search and create app tries to add searchOrCreate based on that resource, on validation it throws an error:

`[
  {
    "Property": "App.searchOrCreates.contactSearchOrCreate.display.description",
    "Message": "does not meet minimum length of 12",
    "Links": ""
  },
  {
    "Property": "App.searchOrCreates.contactSearchOrCreate.key",
    "Message": "must match a \"key\" from a search (options: contactSearch)",
    "Links": "https://github.com/zapier/zapier-platform-schema/blob/v1.0.3/docs/build/schema.md#searchorcreateschema"
  }
]`

I've tried to work it arround by manualy adding this searchOrCreate but I still got error

`[
  {
    "Property": "App.searchOrCreates.contactSearchOrCreate.key",
    "Message": "must match a \"key\" from a search (options: contactSearch)",
    "Links": "https://github.com/zapier/zapier-platform-schema/blob/v1.0.3/docs/build/schema.md#searchorcreateschema"
  }
]`

It appears even if I add that key manualy with contactSearch value

**Comment by BrunoBernardino** [comment]
Hi @amodliszewski thank you for reaching out, I'm sorry to hear you're having issues!

Can you please share your `App` and `resource` definition? You can reach us at contact@zapier.com or if you're comfortable sharing it publicly, it can be here.

**Comment by BrunoBernardino** [comment]
I've confirmed this is the same issue as https://github.com/zapier/zapier-platform-cli/issues/47 and will be adding more information there.

**Comment by patidarkishor777** [comment]
Hi,

I am receiving following error when running a zapier validate --debug command

```
> << 403
<< {"errors": ["App must validate against schema before checking style"]}


Error: "https://zapier.com/api/platform/cli/style-check" returned "403" saying "
App must validate against schema before checking style"
    at C:\Users\ncp\AppData\Roaming\nvm\v6.10.2\node_modules\zapier-platform-cli
\lib\utils\api.js:108:13
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)

Error!
```

> 

Here is my code for searchOrCreate on index.js
```
const findandcreateopportunity = require('./searches/findandcreateopportunity');

searchOrCreates:{
    [findandcreateopportunity] : findandcreateopportunity,

  }
```

Here is my code for searchOrCreate on findandcreateopportunity.js
```
module.exports = {
  
  key: 'createitem',
   // You'll want to provide some helpful display labels and descriptions
   // for users. Zapier will put them into the UX.
   noun: 'CreateItem',
   display: {
     label: 'Create Item',
     description: 'This action will create a Item.'
   },

  // `operation` is where the business logic goes.
  operation: {

    // `inputFields` can define the fields a user could provide,
    // we'll pass them in as `bundle.inputData` later.
    inputFields: [
      {key: 'module',  required: true, type: 'string',label:'Select module', dynamic: 'modulesList.id.operation', helpText: 'Select a module.'},
      getListOfFields
    ],

    perform: createItemAction,   
  },
  


};
```
