### ISSUE TITLE
Error message could be improved when app cannot be found

### ISSUE THREAD

**Issue by craiglabenz** [zapier/zapier-platform-cli#69]
When absentmindedly executing `zapier [whatever]` from the wrong folder, the returned error message is:

```
Looks like your package.json is missing zapier-platform-core or you haven't run npm install yet!
```

Potentially something like the following might help:

```
Could not find your Zapier CLI app. Hint: Are you in the same folder as your `index.js` file?
```

**Comment by nickthetait** [comment]
Seems like this task can be closed. The original error message no longer exists. Seems to have been split into 3 different categories with better explanations.
