### ISSUE TITLE
AdditionalProperty exists in instance when not allowed

### ISSUE THREAD

**Issue by ssshake** [zapier/zapier-platform-cli#77]
Hi I'm just trying to build and publish a sample app and with any app i try I always get these issue

`zapier validate
Validating project locally.

┌─────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Property    │ App.creates.recipe                                                                              │
│ Message     │ additionalProperty "sample" exists in instance when not allowed                                 │
│ Links       │ https://github.com/zapier/zapier-platform-schema/blob/v1.0.10/docs/build/schema.md#createschema │
│                                                                                                               │
│ Property    │ App.creates.recipe                                                                              │
│ Message     │ additionalProperty "outputFields" exists in instance when not allowed                           │
│ Links       │ https://github.com/zapier/zapier-platform-schema/blob/v1.0.10/docs/build/schema.md#createschema │
└─────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────`

**Comment by bcooksey** [comment]
Looks like a bunch of the example apps had the `sample` and `outputField` properties added to the root objects instead of being inside the `operation` properties.

**Comment by ssshake** [comment]
Hmm could this have ever worked? Was it a regression from a recent update?

Couldn't find anything obvious in the error or in some googling so I wasn't sure what to do.

This is not only an issue with these examples on github but the issue occurs with a init with a template


`zapier init . --template=trigger
npm install

zapier validate
Validating project locally.

┌─────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Property    │ App.triggers.recipe                                                                              │
│ Message     │ additionalProperty "sample" exists in instance when not allowed                                  │
│ Links       │ https://github.com/zapier/zapier-platform-schema/blob/v1.0.10/docs/build/schema.md#triggerschema │
│                                                                                                                │
│ Property    │ App.triggers.recipe                                                                              │
│ Message     │ additionalProperty "outputFields" exists in instance when not allowed                            │
│ Links       │ https://github.com/zapier/zapier-platform-schema/blob/v1.0.10/docs/build/schema.md#triggerschema │
└─────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────┘

Make any changes to your project and rerun this command.`

**Comment by bcooksey** [comment]
@ssshake Yea, we did a run through a bunch of the example apps (which power the --template) and added those two properties. Looks like they got added in the wrong spots though.

As a workaround, you should be able to upon up the generated file in the `/triggers` dir and either delete those two properties or move them so they are contained within the `operation` property and it should start passing validation.

**Comment by ssshake** [comment]
👍

**Comment by BrunoBernardino** [comment]
I'll make sure to fix this and also add checks to validate on the `validate-templates` (it only runs `zapier test`) this week.

**Comment by bcooksey** [comment]
Awesome. Odd though, cause I thought `zapier test` also validated the app. 🤷‍♂️

**Comment by BrunoBernardino** [comment]
Alright, I've fixed all the example apps so this should go away now.

As for `npm run validate-templates` not catching it, [this commit will fix it](https://github.com/zapier/zapier-platform-cli/commit/11b5c3061f071e9e8cb92264256920167267d8bb) when it ships in the related PR.
