### ISSUE TITLE
Unable to pass `--use_strict` as a flag during app validation

### ISSUE THREAD

**Issue by Hansenq** [zapier/zapier-platform-cli#78]
Hey there! I'd like to use block-scoped declarations without manually specifying `"use strict"` at the top of every javascript file. An alternate way of doing this is to pass the `--use_strict` flag to `node` or `npm` when the app is run.

I've figured out how to do so so that `zapier test` runs (added it to the "test" command in package.json), but I'm unsure of how to do so for `zapier validate`. Is there a way I can pass build flags to commands such as that?

**Comment by bryanhelmig** [comment]
In the production runtime we don't have access to the arguments to `node` - hence needing the `"use strict"`. I don't believe there is a way to pass arguments down as a result - I could see it being useful for debug flags too.

**Comment by BrunoBernardino** [comment]
Closing this as currently impossible.
