### ISSUE TITLE
altersDynamicFields not being respected

### ISSUE THREAD

**Issue by BrunoBernardino** [zapier/zapier-platform-cli#85]
Some partners have reported an issue where `inputFields` with `altersDynamicFields: true` not being properly refreshed in the Zapier editor unless the "Refresh fields" button is clicked.

Some sample code:

```js
const objectField = (z, bundle) => {
  const appId = bundle.inputData.application_id;
  if (!appId) return [];

  return z.request('someUrl')
    .then(res => {
      return [{
        key: 'object_id',
        required: true,
        label: 'Object',
        choices: jsonArrayToChoices(res.json.data),
       }];
    });
};

...
    inputFields: [
      {
        key: 'application_id',
        required: true,
        label: 'Application',
        dynamic: 'applicationList.id.name',
        altersDynamicFields: true
      },
      objectField,
    ],
...
```

This is has been confirmed and a solution is being investigated.

**Comment by BrunoBernardino** [comment]
Update: the logic above should be working fine, but having `altersDynamicFields` in a field that's being returned from function isn't working properly.

**Comment by jonathanhall** [comment]
I noticed this in Search (or Create) forms. If you check create, it displays the additional fields required in order to create the entity.

However, if the Search form input is dynamic, and changed, it does not refresh the 'create form fields'

**Comment by BrunoBernardino** [comment]
I'm working on finishing this up today (should ship a fix on Monday), so I'll make sure to include that situation in my tests. Thanks @jonathanhall !

**Comment by BrunoBernardino** [comment]
The Search or Create problem is being addressed separately (it's another part of Zapier and we'll update here when that's sorted), but this underlying issue should be fixed now!

**Comment by stevemolitor** [comment]
Going to pick this up tomorrow, but testing locally with the 'Tester' find or create action, the issue seems to be that here, `isDirtyNeeds` is true in the normal case, and false on a dropdown with the 'create' box in a find or create:

https://github.com/zapier/zapier/blob/develop/assets/app/flow/FlowActions.js#L296

Gotta drill down on where `isDirtyNeeds` get sets prior. But for now, dinner.

**Comment by stevemolitor** [comment]
Fix here: https://github.com/zapier/zapier/pull/12278.
